### ISSUE TITLE
Could not pass event EntityDeathEvent error

### ISSUE THREAD

**Issue by notbike** [Rocologo/MobHunting#677] opened 2020-07-25 02:44 UTC
Hi, this error came out of nowhere, i have no idea what this is, something to do with the plugin Mypet?

[22:37:37] [Server thread/ERROR]: Could not pass event EntityDeathEvent to MobHunting v7.5.2
java.lang.NullPointerException: null
	at one.lindegaard.MobHunting.MobHuntingManager.onMobDeath(MobHuntingManager.java:2003) ~[?:?]
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[patched_1.16.1.jar:git-Paper-111]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.1.jar:git-Paper-111]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.1.jar:git-Paper-111]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.1.jar:git-Paper-111]
	at org.bukkit.craftbukkit.v1_16_R1.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:794) ~[patched_1.16.1.jar:git-Paper-111]
	at net.minecraft.server.v1_16_R1.EntityLiving.d(EntityLiving.java:1489) ~[patched_1.16.1.jar:git-Paper-111]
	at net.minecraft.server.v1_16_R1.EntityLiving.die(EntityLiving.java:1417) ~[patched_1.16.1.jar:git-Paper-111]
	at net.minecraft.server.v1_16_R1.EntityLiving.damageEntity(EntityLiving.java:1261) ~[patched_1.16.1.jar:git-Paper-111]
	at net.minecraft.server.v1_16_R1.EntityMonster.damageEntity(EntityMonster.java:52) ~[patched_1.16.1.jar:git-Paper-111]
	at net.minecraft.server.v1_16_R1.EntityZombie.damageEntity(EntityZombie.java:251) ~[patched_1.16.1.jar:git-Paper-111]
	at org.bukkit.craftbukkit.v1_16_R1.entity.CraftLivingEntity.damage(CraftLivingEntity.java:314) ~[patched_1.16.1.jar:git-Paper-111]
	at de.Keyle.MyPet.skill.skills.StompImpl.lambda$apply$0(StompImpl.java:128) ~[?:?]
	at java.util.Optional.ifPresent(Unknown Source) ~[?:1.8.0_251]
	at de.Keyle.MyPet.skill.skills.StompImpl.apply(StompImpl.java:94) ~[?:?]
	at de.Keyle.MyPet.listeners.MyPetEntityListener.onMyPetDamageMonitor(MyPetEntityListener.java:386) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor596.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.1.jar:git-Paper-111]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.1.jar:git-Paper-111]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.1.jar:git-Paper-111]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.1.jar:git-Paper-111]
	at org.bukkit.craftbukkit.v1_16_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:247) ~[patched_1.16.1.jar:git-Paper-111]
	at org.bukkit.craftbukkit.v1_16_R1.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:1035) ~[patched_1.16.1.jar:git-Paper-111]
	at org.bukkit.craftbukkit.v1_16_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:922) ~[patched_1.16.1.jar:git-Paper-111]
	at org.bukkit.craftbukkit.v1_16_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:878) ~[patched_1.16.1.jar:git-Paper-111]
	at org.bukkit.craftbukkit.v1_16_R1.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:1067) ~[patched_1.16.1.jar:git-Paper-111]
	at net.minecraft.server.v1_16_R1.EntityLiving.damageEntity0(EntityLiving.java:1823) ~[patched_1.16.1.jar:git-Paper-111]
	at net.minecraft.server.v1_16_R1.EntityLiving.damageEntity(EntityLiving.java:1151) ~[patched_1.16.1.jar:git-Paper-111]
	at net.minecraft.server.v1_16_R1.EntityMonster.damageEntity(EntityMonster.java:52) ~[patched_1.16.1.jar:git-Paper-111]
	at net.minecraft.server.v1_16_R1.EntityZombie.damageEntity(EntityZombie.java:251) ~[patched_1.16.1.jar:git-Paper-111]
	at de.Keyle.MyPet.compat.v1_16_R1.entity.EntityMyPet.attack(EntityMyPet.java:382) ~[?:?]
	at de.Keyle.MyPet.compat.v1_16_R1.entity.ai.attack.MeleeAttack.tick(MeleeAttack.java:152) ~[?:?]
	at de.Keyle.MyPet.api.entity.ai.AIGoalSelector.tick(AIGoalSelector.java:141) ~[?:?]
	at de.Keyle.MyPet.compat.v1_16_R1.entity.EntityMyPet.doMyPetTick(EntityMyPet.java:1136) ~[?:?]
	at de.Keyle.MyPet.compat.v1_16_R1.entity.EntityMyPet.movementTick(EntityMyPet.java:1014) ~[?:?]
	at de.Keyle.MyPet.compat.v1_16_R1.entity.types.EntityMyFox.movementTick(EntityMyFox.java:183) ~[?:?]
	at net.minecraft.server.v1_16_R1.EntityLiving.tick(EntityLiving.java:2465) ~[patched_1.16.1.jar:git-Paper-111]
	at net.minecraft.server.v1_16_R1.EntityInsentient.tick(EntityInsentient.java:306) ~[patched_1.16.1.jar:git-Paper-111]
	at de.Keyle.MyPet.compat.v1_16_R1.entity.EntityMyPet.tick(EntityMyPet.java:1336) ~[?:?]
	at net.minecraft.server.v1_16_R1.WorldServer.entityJoinedWorld(WorldServer.java:831) ~[patched_1.16.1.jar:git-Paper-111]
	at net.minecraft.server.v1_16_R1.World.a(World.java:932) ~[patched_1.16.1.jar:git-Paper-111]
	at net.minecraft.server.v1_16_R1.WorldServer.doTick(WorldServer.java:525) ~[patched_1.16.1.jar:git-Paper-111]
	at net.minecraft.server.v1_16_R1.MinecraftServer.b(MinecraftServer.java:1353) ~[patched_1.16.1.jar:git-Paper-111]
	at net.minecraft.server.v1_16_R1.DedicatedServer.b(DedicatedServer.java:377) ~[patched_1.16.1.jar:git-Paper-111]
	at net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:1212) ~[patched_1.16.1.jar:git-Paper-111]
	at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1000) ~[patched_1.16.1.jar:git-Paper-111]
	at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-111]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]

**https://pastebin.com/CZXMmiEi**
**for easy visibility**

Server 1.16.1
mobhunting 7.5.2
paperspigot

thank you!

**Comment by Rocologo** [comment] 2020-07-25 02:47
Please post the full error text including Caused by...

**Comment by notbike** [comment] 2020-07-25 02:50
sorry, I have no idea what it's caused by, it just randomly shows up. and this is the full error text, there's nothing before and after that, just conversations

**Comment by Rocologo** [comment] 2020-07-25 06:28
Okay thank you. I had not seen that there was a MyPet snapshot for 1.16, I will test MyPet with MobHuntin to see if I can reproduce the bug.

**Comment by Rocologo** [comment] 2020-07-25 06:58
Strange. Do you know what trigger this error? It looks like the killer is null ???? Are you able to reproduce this error?

**Comment by Rocologo** [comment] 2020-07-25 06:59
(I testet MyPet on my Test server and everything works perfectly, I get a reward when my pet kills a mob) so I need you help to find out when this happens.

**Comment by Rocologo** [comment] 2020-07-26 07:18
If you enable debug using "/mh debug" and show me the lines before the error and after, I hope I will get some information on whats going on.

**Comment by notbike** [comment] 2020-08-05 15:21
Hi @Rocologo ！！ I got the debug log!

https://pastebin.com/fR8twph2

thank you!

**Comment by Rocologo** [comment] 2020-08-08 18:42
Thank you. That helped me alot. I think this is fixed in  build 1074

https://fractal.lindegaard.one:8181/job/MobHunting/

**Closed** 2020-08-15 21:06 UTC
Labels: Fixed - To be tested
