### ISSUE TITLE
Unable to add money.

### ISSUE THREAD

**Issue by Sikatsu** [Rocologo/MobHunting#534] opened 2019-07-19 18:34 UTC
Not sure, but since 6.7.7 it seems to throw this error.

http://prntscr.com/ohfl5g

**Comment by Rocologo** [comment] 2019-07-19 19:42
Sorry,  but you have to explain what you are doing???



Sendt fra Samsung Galaxy S10+


-------- Oprindelig besked --------
Fra: Sikatsu <notifications@github.com>
Dato: 19/07/2019 21.34 (GMT+02:00)
Til: Rocologo/MobHunting <MobHunting@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Emne: [Rocologo/MobHunting] Unable to add money. (#534)


Not sure, but since 6.7.7 it seems to throw this error.

http://prntscr.com/ohfl5g

**Comment by Rocologo** [comment] 2019-07-19 19:52
Im not even sure that this error is from MobHunting?

**Comment by Sikatsu** [comment] 2019-07-19 19:58
Since the update, everytime when I kill something it says ''Unable to add money.'' There isn't much else to explain.

**Comment by Rocologo** [comment] 2019-07-20 05:59
I promise you I have killed a lot of mobs when testing and I dont get this message. 

Do you have this message in your lang file? I dont recognize it?

**Comment by Sikatsu** [comment] 2019-07-20 13:32
Well, disabling plugin one by one and it turned out to be mobhunting. Seems theres someone else in the discussion thread with a similiar issue.

**Comment by kelso6969** [comment] 2019-07-21 00:03
I get the same message when killing things now.

**Comment by kelso6969** [comment] 2019-07-21 00:03
Roll back to previous version makes the error go away

**Comment by Rocologo** [comment] 2019-07-21 07:02
it seems that your economy plugin fails to deposit the money. which economy plugin do you use?

**Comment by Sikatsu** [comment] 2019-07-21 07:03
Vault. It happens since the last version indeed when support for Reserve? Was added.

**Comment by Rocologo** [comment] 2019-07-21 07:34
Yes. Bug is introduced when I added support for Reserve.

Vault is not an economy plugin. Vault is an API to you economy plugin.  BagOfGold, Craftconomy and Essentials is economy plugins. I have done a lot of testing with BagOfGold,  but not with Essential. So I will try with essentials on my test server.

**Comment by Sikatsu** [comment] 2019-07-21 07:36
Ahh, then essentialsX in that case.

**Comment by Rocologo** [comment] 2019-07-21 07:37
Perfect is will test with EssentialsX then

**Comment by Sikatsu** [comment] 2019-07-21 07:40
It's also a visual bug, the money DOES get added I believe.

**Comment by Rocologo** [comment] 2019-07-21 07:50
Ahh... I can easily add the text "Unable to add money." but that would be a bad way to solve this issue. 

I cant remember if you drop bags on the ground to be picked up, or if the money goes directly into the balance? (I want to test the same setup as you have)

**Comment by Rocologo** [comment] 2019-07-21 07:59
Now I can reproduce the error. :-) Using EssentialsX (and dont drop money on the ground). Now I can find a solution.

**Comment by Rocologo** [comment] 2019-07-21 08:25
I think i have found the problem and the solution now. I just need to do some more testing.

**Comment by Rocologo** [comment] 2019-07-21 09:00
You can help testing if you have time
https://fractal.lindegaard.one:8181/job/MobHunting/848

**Comment by Rocologo** [comment] 2019-07-21 09:05
Dont... its not solved yet

**Comment by Rocologo** [comment] 2019-07-21 09:18
(Im on vacation and my internet is super slow, so testing is very difficult for me :-( )

**Comment by Sikatsu** [comment] 2019-07-21 13:35
For now I downgraded the version, hope you'll find a fix. ^^

Enjoy your vacation though!

**Comment by Rocologo** [comment] 2019-07-21 13:53
I always find a fix :-)

**Comment by Rocologo** [comment] 2019-07-21 19:31
Fixed in v2.7.2

**Comment by Rocologo** [comment] 2019-07-21 19:59
I was a stupid bug i had made :-)

**Closed by Rocologo** 2019-07-21 19:59 UTC

**Comment by Sikatsu** [comment] 2019-07-21 20:10
2.7.2? You meant 6.7.8? Haha

Thanks for fixing it!

**Comment by Rocologo** [comment] 2019-07-22 02:27
Yes. 2.7.2 is newest version of BagOfGold where I fixed 2 gringotts style bugs.
