### ISSUE TITLE
Happyhour and fishing

### ISSUE THREAD

**Issue by Sikatsu** [Rocologo/MobHunting#136] opened 2017-02-08 22:19 UTC
HappyHour doesn't apply on fishing using 4.4.1. (Neither shows the message x2.0 HappyHour)

**Comment by Rocologo** [comment] 2017-02-09 08:40
Confirmed. The fishingevent is not stable yet because of the mcmmo problems, so I introduced a bug by mistake.

The bug is fixed in V4.4.2 (Will be released today)

**Closed by Rocologo** 2017-02-09 08:40 UTC

**Comment by Sikatsu** [comment] 2017-02-09 09:05
Thanks!
