### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException: 19

### ISSUE THREAD

**Issue by FlashLight34** [Rocologo/MobHunting#63] opened 2016-06-27 23:55 UTC
Mobhunting 3.2.3
[01:42:08 WARN]: Exception in thread "MH TaskThread" 
[01:42:08 WARN]: java.lang.ArrayIndexOutOfBoundsException: 19
[01:42:08 WARN]: at sun.util.calendar.BaseCalendar.getCalendarDateFromFixedDate(BaseCalendar.java:453)
[01:42:08 WARN]: at java.util.GregorianCalendar.computeFields(GregorianCalendar.java:2397)
[01:42:08 WARN]: at java.util.GregorianCalendar.computeFields(GregorianCalendar.java:2312)
[01:42:08 WARN]: at java.util.Calendar.setTimeInMillis(Calendar.java:1804)
[01:42:08 WARN]: at java.util.Calendar.setTime(Calendar.java:1770)
[01:42:08 WARN]: at java.text.SimpleDateFormat.format(SimpleDateFormat.java:943)
[01:42:08 WARN]: at java.text.SimpleDateFormat.format(SimpleDateFormat.java:936)
[01:42:08 WARN]: at java.text.DateFormat.format(DateFormat.java:345)
[01:42:08 WARN]: at net.minecraft.server.v1_9_R2.UserCache$BanEntrySerializer.a(UserCache.java:299)
[01:42:08 WARN]: at net.minecraft.server.v1_9_R2.UserCache$BanEntrySerializer.serialize(UserCache.java:345)
[01:42:08 WARN]: at net.minecraft.server.v1_9_R2.UserCache$BanEntrySerializer.serialize(UserCache.java:1)
[01:42:08 WARN]: at com.google.gson.TreeTypeAdapter.write(TreeTypeAdapter.java:70)
[01:42:08 WARN]: at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:68)
[01:42:08 WARN]: at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.write(CollectionTypeAdapterFactory.java:96)
[01:42:08 WARN]: at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.write(CollectionTypeAdapterFactory.java:60)
[01:42:08 WARN]: at com.google.gson.Gson.toJson(Gson.java:593)
[01:42:08 WARN]: at com.google.gson.Gson.toJson(Gson.java:572)
[01:42:08 WARN]: at com.google.gson.Gson.toJson(Gson.java:527)
[01:42:08 WARN]: at com.google.gson.Gson.toJson(Gson.java:507)
[01:42:08 WARN]: at net.minecraft.server.v1_9_R2.UserCache.c(UserCache.java:231)
[01:42:08 WARN]: at net.minecraft.server.v1_9_R2.UserCache.getProfile(UserCache.java:164)
[01:42:08 WARN]: at org.bukkit.craftbukkit.v1_9_R2.CraftServer.getOfflinePlayer(CraftServer.java:1310)
[01:42:08 WARN]: at org.bukkit.Bukkit.getOfflinePlayer(Bukkit.java:749)
[01:42:08 WARN]: at one.lindegaard.MobHunting.storage.SQLiteDataStore.loadPlayerStats(SQLiteDataStore.java:148)
[01:42:08 WARN]: at one.lindegaard.MobHunting.storage.asynch.StatRetrieverTask.run(StatRetrieverTask.java:55)
[01:42:08 WARN]: at one.lindegaard.MobHunting.storage.asynch.StatRetrieverTask.run(StatRetrieverTask.java:1)
[01:42:08 WARN]: at one.lindegaard.MobHunting.storage.DataStoreManager$TaskThread.run(DataStoreManager.java:381)

**Comment by Rocologo** [comment] 2016-06-28 21:44
This is actually a bug in this method 
[01:42:08 WARN]: java.lang.ArrayIndexOutOfBoundsException: 19
[01:42:08 WARN]: at sun.util.calendar.BaseCalendar.getCalendarDateFromFixedDate(BaseCalendar.java:453)

called from 
01:42:08 WARN]: at org.bukkit.Bukkit.getOfflinePlayer(Bukkit.java:749)

Sometimes getOfflinePlayer return a wrong format. I have updated my plugin in V3.2.4 so it writes "unknow" in the playername when/if this warning/error happens.

This is the best I can do until Bukkit get this fixed. :-(

**Comment by Rocologo** [comment] 2016-06-29 18:51
I have thought about this, maybe yhis is related to the freezing problem. Maybe the above warning keeps an connection open. Hmmm. I have reopened the ticket and will study the source code to, see if I some can make sure that there is no open connections.

**Comment by Rocologo** [comment] 2016-07-01 12:31
I think I found the bug, but it is hard to test because I cant reproduce the bug.

Fixed in V3.2.7

**Closed by Rocologo** 2016-07-01 12:31 UTC
Labels: bug
