### ISSUE TITLE
MH heads corrupted - Don't want 'Bag of Gold'

### ISSUE THREAD

**Issue by datsme** [Rocologo/MobHunting#182] opened 2017-03-05 17:54 UTC
MH Version 4.6.1 
git-Spigot-d4f98a3-cb61ac0 (MC: 1.11.2)
Gringotts 2.9

I have Gringotts disabled,
drop-money-on-ground-itemtype: ITEM,
drop-money-on-ground-item: EMERALD
drop-money-use-item-as-currency: false
The emerald currency and scoreboard features are cool but we really use your mod for the mob head drops however,  the heads that drop now show NBT Data and have the wrong head (Bag of Gold) and also show an emerald value.
(see attached image)
When it drops a head all we want is the plain mob head. No emerald value no visible tags to the players
Is there a way we can go back to that?
![mh_cap](https://cloud.githubusercontent.com/assets/12632170/23589804/dd0e12c4-0199-11e7-90f6-3ae4e9469320.png)

**Comment by Rocologo** [comment] 2017-03-05 20:00
You can remove the Lores by installing ProtocolLib

And set the pig_zombie_head_prize to 0 zero to remove the value. (10 emeralds)

And if you use Gringotts, why do you then disable integration?

**Comment by datsme** [comment] 2017-03-06 18:56
I have protocolLib 4.2.0

This is at 0 
  zombie-pigman: '4:8'
  zombie-pigman-cmd: mobhunt head give {player} Pig_Zombie|give {player} iron_ingot 1
  zombie-pigman-cmd-desc: You got a Zombie Pigman skull and an Iron ingot.
  zombie-pigman-cmd-run-chance: 0.1
  zombie-pigman-head-prize: '0'

Disabled due to previous issues you said would be in next version - Closed ticket

Also, when enabled and killing mobs it lags the game same as if I set 
drop-money-on-ground: false
As soon as mobs die there is a lag spike and I know its this mod because I disable it and the lag is gone. Have not figured out though if its between yours and gringotts or the leader board etc in yours. In either case disabling support seriously limits the lag.

**Comment by Rocologo** [comment] 2017-03-06 19:40
I only close tickets when i think the issue is fixed or if my questions not being answered. But they can easily be opened again.

I you use gringotts you should not disable integration and use Emeralds as a rewards. I have tried Gringotts many times and I get no lag at all when I kill mobs. So start looking for the reason for the lag instead of disable Gringotts integration if you want to use gringotts. Or try using another item than Emeralds.

**Comment by Rocologo** [comment] 2017-03-06 19:42
Try enable debug and do a kill and let me see the server log including the saving at leaderboard update information. 

How often do you save and update leaderboards?

**Comment by Rocologo** [comment] 2017-03-06 19:44
PS Heads without the right texture cant be fixed you will have to generate new heads using /mh head

**Comment by Rocologo** [comment] 2017-03-06 19:46
Does the head look ok if you use /mh head drop or mh head give ?

**Comment by Rocologo** [comment] 2017-03-06 20:29
I just found your previous ticket. The issue was that the server crashed when you killed a mob, i fixed that and closed the ticket.

**Comment by datsme** [comment] 2017-03-06 22:14
I will run the debug later in the early morning when no players are on and send the log then.

leaderboard-update-period: 6000

The heads have the correct texture when I use /mh head give but the lores seem to randomly appear and disappear when hovered over in inventory. In contrary the ones from your previous versions that are mounted on a trophy wall do not display this lore issue if broken and placed in inventory. 

Thanks again for your support!

**Comment by Rocologo** [comment] 2017-03-06 23:12
I use the information in the lores to store information about the value and the uuid, so that the head and the value can survive a server restart. I use ProtocolLib to hide the Hidden: information but it seems not to work in all situation. This is not something i can fix, because i dont know enough about the packets send between the server and the client.

I cant fix old heads not working, you have to drop the heads and give yourself some new ones.

**Comment by datsme** [comment] 2017-03-07 08:24
I enabled Gringotts support again and it looks like it is working fine now.
As for the lag, I believe I owe you an apology. With no players logged on and it being 2 am so, I am sure the server traffic is low, I could not reproduce the lag on kill issue. It must be caused by server lag/load issue. So for this again I am sorry!  I use APEX so I am not sure how they stack up as far as speed but for $20 a month I can live with some lag that is unless my players would like to start donating LOL.

As for the heads, you said you use lore to store information. Is this new/change from previous versions? Minecraft can see there is a difference because heads dropped now through MH no longer stack with heads dropped from previous versions. Also if I give a player a new mob head via /mh head give it still will display randomly the hidden lore as not so hidden LOL

**Comment by Rocologo** [comment] 2017-03-07 08:41
Yes you cant stack the heads anymore, because all the heads and the bag of gold have a unique UUID in the lores. I need this to keep track of the value on a server restart. 

In teory i should be able to make them stack again, but I have decided to take a break from minecraft plugin development. 

As for the lag, some of the other users use LagMonitor to monitor their servers. The found some potential lag risk, when players logged in, but this is fixed some time ago, and they have confirmed that the solution works. If there had been other lag issues they would have warned me. (Unfortunately I dont think they use Gringotts, and this could of cause make a difference)

I know that the solution where i hide some of the lores using ProtocolLib, isn't bullet proff and because it is "hacking" the protocol there is no really good documentation on this. If you can find a way to reproduce the problem, i can ask the dev of ProtocolLib if he has an solution.

**Comment by datsme** [comment] 2017-03-07 09:24
Thank you for your help. It will be sad to see you go but its understandable everyone needs a break!
I guess I will look around for a different mod that drops heads then.

**Comment by Rocologo** [comment] 2017-03-08 16:27
Okay, then i close this ticket. (If you dont use MobHunting)

**Closed by Rocologo** 2017-03-08 16:27 UTC
