### ISSUE TITLE
mob hunting NPC

### ISSUE THREAD

**Issue by silverkin** [Rocologo/MobHunting#35] opened 2016-05-19 17:41 UTC
hello guys , i just use your latest version of mob hunting on my server v1.9.2

i tried to create mob hunting NPC using /mh npc create total_kills alltime 1 &  /mh npc create zombie_kills week 1 , but the NPC will disappear

when i check bukkitgui  i receive this warning message

[WARN] [MobHunting] NPC ID=43 has an invalid StatType. Resetting to total_kill

**Comment by Rocologo** [comment] 2016-05-19 18:37
Which server do you use? Spigot, Craftbukkit or ?

The warning "[WARN] [MobHunting] NPC ID=43 has an invalid StatType. Resetting to total_kill" should not delete the NPC.

Which version of Citizens do you use?

**Comment by silverkin** [comment] 2016-05-19 19:39
I use Spigot 1.9.2 , and citizes 2.0.17 (alpha 1 for MC 1.9)
<http://dev.bukkit.org/bukkit-plugins/citizens/files/53-2-0-17-alpha-1-for-mc-1-9/>

**Comment by silverkin** [comment] 2016-05-20 05:05
goody another problem came up , i update mob hunting to latest version
3.0.2  , Sever errors always showing on my bukkit GUI .

Severe       Could not pass eventn inventoryclickEvent to mob hunting v3.0.2

**Comment by silverkin** [comment] 2016-05-20 05:10
1:08:55 PM Caused by: java.lang.NullPointerException
1:08:55 PM at
one.lindegaard.MobHunting.achievements.AchievementManager.onInventoryClick(AchievementManager.java:662)
~[?:?]

**Comment by Rocologo** [comment] 2016-05-20 13:08
The inventoryClickEvent error will be fixed in next release V3.0.3 - today.

**Comment by silverkin** [comment] 2016-05-20 14:22
how about the /mh npc create ? do you have any idea how to fix this? while
creating npc for mob hunting top player NPC will disappear

**Comment by Rocologo** [comment] 2016-05-20 15:00
I dont have a clue. I cant reproduce it and if you dont get any errors in the console I dont know where to find the problem.

It works all the time on my computer. So I need your help to investigate when and why it happens???

**Comment by Rocologo** [comment] 2016-05-20 16:28
HI again. I have just tested "/mh npc create total_kills alltime 1" and found a problem. No matter what StatType I choose I get the warning in the console "The warning "[WARN] [MobHunting] NPC ID=43 has an invalid StatType. Resetting to total_kill" should not delete the NPC." and this is an error I will fix fast. 

BUT it does not delete the NPC or make it disappear like you describe?????

**Comment by silverkin** [comment] 2016-05-20 16:44
it doesn't delete, it will disappear,  thanks for the fast reply hope it
will be fix soon, because your plugin in is so awesome :) thanks

**Comment by Rocologo** [comment] 2016-05-20 21:41
My plugin does not despawn any NPC's so it is very strange.

**Comment by Rocologo** [comment] 2016-05-20 22:20
Please test the /mh npc create total_kills alltime 1 & /mh npc create zombie_kills week 1

The error  "The warning "[WARN] [MobHunting] NPC ID=43 has an invalid StatType. Resetting to total_kill" should be gone now. I not sure if this the root cause for your problem. But I fixed the problem with the wrong Stattype.

Please let me know if this solves your problem?

**Comment by silverkin** [comment] 2016-05-21 04:54
when i stop my server , I recieve this message

12:52:49 PM [INFO] [MobHunting] Disabling MobHunting v3.0.4
12:52:49 PM [WARN] Exception in thread "MH TaskThread"
12:52:49 PM [WARN] java.lang.NullPointerException
12:52:49 PM [WARN] at
one.lindegaard.MobHunting.storage.DataStoreManager$TaskThread.run(DataStoreManager.java:400)

**Comment by Rocologo** [comment] 2016-05-21 06:53
This will be fixed in V3.0.5 

> when i stop my server , I recieve this message



> 12:52:49 PM [INFO] [MobHunting] Disabling MobHunting v3.0.4
> 12:52:49 PM [WARN] Exception in thread "MH TaskThread"
> 12:52:49 PM [WARN] java.lang.NullPointerException
> 12:52:49 PM [WARN] at
> one.lindegaard.MobHunting.storage.DataStoreManager$TaskThread.run(DataStoreManager.java:400)
> …

What about the /mh npc .... command?

**Comment by silverkin** [comment] 2016-05-21 07:35
i tried the /mh npc so far no error or bug  happend i will monitor the NPC
when other players log in. . thanks

**Comment by silverkin** [comment] 2016-05-21 07:41
I just wnt to ask i made a /mh npc create creeper_kills week 1 , i don't
have any player registered on my server that named  NO KILLS
so NPC NO KILLS appear . and when i put the sign the NPC disappear is that
necessary? will the NPC show again when players kill creeper?



​

**Comment by silverkin** [comment] 2016-05-21 15:31
another problem came up , when i make an MH sign for the top players .....
and i use lockette plugin ,  when a player put sign on the chest the name
will appear on sign is the top player for mob hunting and they cannot
destroy the sign

**Comment by Rocologo** [comment] 2016-05-21 18:59
It says NO KILLS because you have not killed any creepers this week. 

But it is first time you tell me that you place the sign while the NPC is called NO KILLS. I have never tried that so now i have something new to test. 

I dont fully understand what you do with a chest, lockette and a sign. Maybe you could make a screenshot?

**Comment by Rocologo** [comment] 2016-05-21 21:57
I could easily create a NPC like this: "/mh npc create Slime_Kills Week 1" and create a sign next step. No problem. See the screenshot. Maybe you have an conflicting plugin? Do you use other NPC plugins?
![2016-05-21_23 53 33](https://cloud.githubusercontent.com/assets/1008133/15451006/85362d9c-1faf-11e6-924b-7b3ddbe4572f.png)

**Comment by silverkin** [comment] 2016-05-22 01:42
can i ask? what citizens version do you use? because i cant' use the
jenkins latest version 2.0.18 some error message when i use 2.0.18 that's
why i downgrade my citizens 2.0.17

i use plugin

- NPC SHOP
- SENTRY
- CITIZENS 2 2.0.17 snapshot



is it possible that the /mh npc conflict any of the 3 plugin that i use?

**Comment by silverkin** [comment] 2016-05-22 01:44
https://www.spigotmc.org/resources/shop.8185/     <----- this the shop with
NPC

and also i use STABLES plugin , plus the 3 plugin i mentioned earlier

**Comment by silverkin** [comment] 2016-05-22 05:13
Hello and good day ,

i removed the Sentry , shop NPC , and then type /mh npc create total_kills
alltime 1

NPC was created but no NPC show up.


and in the pic that's the plugin i used








​

**Comment by Rocologo** [comment] 2016-05-22 06:56
You have to use citizens 2.0.17 (Build 1356) when you use Spigot 1.9.2. Build 1356 is latest version which works with Minecraft 1.9.2. I have upgraded to 1.9.4 so I have tested with 2.0.18 Build 1364. I dont think the citizens version is your problem. I use sentry to and I integrate to Sentry so you are able to get a reward if you kill a sentry. 

Im still thinking about a conflict with one of your other NPC plugins. So I will take a look at the 
SHOP NPC https://www.spigotmc.org/resources/shop.8185/ I will test SHOP NPC on my test server.

And the I have to google " STABLES" because I dont know that plugin. 

I dont understand when you write "NPC was created but no NPC show up." If the NPC is created it also show up??? Or what do you mean? The picture is missing? :-)

**Comment by silverkin** [comment] 2016-05-22 07:42
if i type /mh npc create total_kills alltime 1 , no NPC will appear , but
in the chat box it says NPC was created.

**Comment by Rocologo** [comment] 2016-05-22 07:44
Okay... its really strange. I downloaded SHOP NPC but the newest version does not work on MC 1.9.2, and I cant find SHOP NPC for 1.9.2???

**Comment by Rocologo** [comment] 2016-05-22 07:46
Is there a reason why you have not upgraded to MC 1.9.4?

**Comment by Rocologo** [comment] 2016-05-22 07:50
Maybe the NPC is just despawned .... try typing (use the id you get when its created)

/npc spawn <id>

and tell me if the the NPC spawns.

**Comment by silverkin** [comment] 2016-05-22 14:40
im new in making server, but i didn't expect that many players will join my
server. the problem is , i don't know yet what to do upgrading my server
from 1.9.2 to 1.9.4 i am afraid that some player data or land will be lose
:)

1.9.2 is buggy?

ok i will try the /npc spawn


sorry for asking to many questions  and thank you for your fast respond :)

**Comment by Rocologo** [comment] 2016-05-24 06:38
Its okay that you ask questions. I don't think the core problem is that you are on 1.9.2. 26,5% of the servers the use MobHunting = 63 servere uses Minecraft 1.9.2 and I dont hear about this issue from others than you. So I dont think 1.9.2 is the problem. 

Can you tell me if it is the same NPC all the time? Is it the same ID? I have just found a bug when a user created a MasterMoobHunter on NPC ID = 0. 

I think it is a seldom bug or a conflict with another plugin. Im sorry I cant solve this one fast. But without an error text in the console, and when I cant replicate the error its very hard to find this bug. It could be a bug in another plugin as well. The thing is that I dont remove NPC unless you write "/mh npc remove ID"

**Comment by silverkin** [comment] 2016-05-24 12:32
i change my server to 1.9.4 , try to make the npc for mob hunting still no
luck , and i think its the citizens 2 plugin has a problem , i use the
citizens 2 @ jekins build #1369 v2.0.18-snapshot when i create using /NPC
create then the name of the NPC it was successfuly created but i can't see
any NPC

**Comment by silverkin** [comment] 2016-05-24 12:40
what citizens 2 build should i use? because i tried to remove SHOP plugin ,
STABLES plugin then try the /mh npc create still no NPC showing up.

my plugin:

AncientGates
AntiSpam
Areashop
AutoSaveWorld
BungeePortals
Bungeetablistplus
chestcommands
chestregen
citizens 2
compatnocheatplus
coreprotect
creeperheal
customScoreboard
customskins
Essentials
FirstJoinPlus
GroupManager
Healthbar
Heavyspleef
HolographicDisplay
iconomy_Recreation
Infernal mobs
Infinity Dispenser
jobs
Lockette
mcMMO
Minigames
Mobhunting *
Multiverse-core
multiworld
mypet
mythicmobs
nocheatplus
perworldchatplus
perworldinventory
playervaults
protocolib
sentry
shop (npc shop)
showcasestandalone
signcolors
supervanish
Tpsign
TreeAssist
vault
wizardlyMagic
WorldEdit
worldGuard

**Comment by Rocologo** [comment] 2016-05-24 16:48
On my test server i use 
SpigotMC 1.9.4
Citizens v2.0.18-SNAPSHOT (build 1364)
Sentry 1.9.1 Build 36)
MobHunting 3.0.7 
Shop 2.0.5
WorldGuard 6.1
worldEdit 6.1
MyPet 2.1.1
Mobarena 0.97.1
BossBarAPI 2.4.0
TitleManager 1.5.11
MythicMobs 2.4.3
EssentialsX 2.0.1 Build 334
Vault 1.5.6
ProtocolLib 4.0.1
Gamemodecontrol 1.2.0
PermissionsEX 1.23.4
EditableSign 2.2.0
LibsDisguises 9.0.6
PlugMan 2.1.0

When I use all these everything seems to works for me.

I dont have the time to test all your plugins, but if you can disable them one by one until you find out which one conflicts with MobHunting, then I will test it and try to make them work together.

**Comment by Rocologo** [comment] 2016-05-24 20:52
I just noticed that you wrote that you could not create a npc with "/npc create ... " this tells me that it is citizens which is your problem. Have you given your self the need permissions to create npcs? If you can create a standard npc with  /npc create you will not be able to use mastermobhunters in mobhunting.

**Comment by silverkin** [comment] 2016-05-25 03:00
ok i will try to make a fresh install server then put the plugin one by
one...  thanks :)

**Comment by Rocologo** [comment] 2016-05-25 04:09
You should  start with citizens. Make sure that you can create a npc witn /npc create...

**Comment by Rocologo** [comment] 2016-05-25 04:09
Without mobhunting installed

**Comment by silverkin** [comment] 2016-05-25 08:20
i download the latest update of mobhunting , i can create NPC and another
problem came up...... i can't create sign [MHnnn] or [HMnnn] <--- example
on your tutorial



​

**Comment by Rocologo** [comment] 2016-05-25 12:39
What happens when you try? I hope you write [mh1] and not nnn ? right? :-) how does the sign look like when you try?  You have to tell me what happens?

**Comment by silverkin** [comment] 2016-05-25 18:10
when i click the NPC with stick to check there ID's i see ID=0 2nd NPC is 1
3rd is 2

so i put at the sign first line [mh0] or [MH0] there's no Error on my GUI ,
 i created the sign but only the [mh0] i saw on the sign

**Comment by silverkin** [comment] 2016-05-25 18:12
does skin bug on 1.9.2 and 1.9.4?

**Comment by Rocologo** [comment] 2016-05-25 18:50
What about [mh1] and [mh2] does they work? I have had some problems with id=0 maybe i havnt found all errors when id=0

**Comment by silverkin** [comment] 2016-05-27 02:50
[mh1] and [mh2] doesn't work also :(

**Comment by Rocologo** [comment] 2016-05-27 03:00
Let me see your serverlog on restart and when you create a NPC and a sign . There must be some kind of error. And enable kill_debug in config.yml before restart.

**Comment by silverkin** [comment] 2016-05-27 11:46
Can i ask? what causes this error?

6:57:15 PM [WARN] [MobHunting] Task #1045 for MobHunting v3.0.7 generated
an exception
6:57:15 PM java.lang.NullPointerException
6:57:15 PM at
one.lindegaard.MobHunting.bounty.BountyManager.addBounty(BountyManager.java:91)
~[?:?]
6:57:15 PM at
one.lindegaard.MobHunting.bounty.BountyManager.createRandomBounty(BountyManager.java:513)
~[?:?]
6:57:15 PM at
one.lindegaard.MobHunting.bounty.BountyManager$1.run(BountyManager.java:54)
~[?:?]
6:57:15 PM at
org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftTask.run(CraftTask.java:71)
~[main.jar:git-Spigot-8a048fe-a022dd2]
6:57:15 PM at
org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350)
[main.jar:git-Spigot-8a048fe-a022dd2]
6:57:15 PM at
net.minecraft.server.v1_9_R2.MinecraftServer.D(MinecraftServer.java:734)
[main.jar:git-Spigot-8a048fe-a022dd2]
6:57:15 PM at
net.minecraft.server.v1_9_R2.DedicatedServer.D(DedicatedServer.java:399)
[main.jar:git-Spigot-8a048fe-a022dd2]
6:57:15 PM at
net.minecraft.server.v1_9_R2.MinecraftServer.C(MinecraftServer.java:665)
[main.jar:git-Spigot-8a048fe-a022dd2]
6:57:15 PM at
net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:564)
[main.jar:git-Spigot-8a048fe-a022dd2]
6:57:15 PM at java.lang.Thread.run(Thread.java:745) [?:1.8.0_92]

**Comment by Rocologo** [comment] 2016-05-27 19:56
It looks like a bug. I will check it during the weekend


Sent from Samsung tablet.

-------- Original message --------

**Comment by Rocologo** [comment] 2016-05-30 07:14
I need help to solve this. Ideally I need someone to login to my server and help testing together with me. So I can add some more debug code to find the problem. I can partly see what's wrong, but I don't understand why this happens yet. What you could do is to enable kill_debug in config.yml restart your server and show me the log next time this problem happens.

**Comment by silverkin** [comment] 2016-05-30 14:52
ok i will try it when i get back.. i'm out of town for 1 night only. maybe
tomorrow.

**Comment by silverkin** [comment] 2016-06-01 15:04
hello rocologo , i updated my mobhunting to 3.1.0 today , when i start my
server , CPU usage always in 100%

**Comment by Rocologo** [comment] 2016-06-01 18:47
Ups, that does not sound good. Im having birthday today so i cant fix it until tomorrow.

**Comment by Rocologo** [comment] 2016-06-01 19:44
V3.1.1 fixes the 100 % CPU usage, sorry for that error.

**Comment by silverkin** [comment] 2016-06-02 03:34
Thanks :)

**Comment by silverkin** [comment] 2016-06-02 19:50
when i put a sign [MH0] [MH1] [MH2]

i got this message on my gui

3:48:32 AM [ERROR] Could not pass event SignChangeEvent to MobHunting v3.1.4
3:48:32 AM org.bukkit.event.EventException
3:48:32 AM at
org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310)
~[survival.jar:git-Spigot-8a048fe-a022dd2]
3:48:32 AM at
org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
~[survival.jar:git-Spigot-8a048fe-a022dd2]
3:48:32 AM at
org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
[survival.jar:git-Spigot-8a048fe-a022dd2]
3:48:32 AM at
org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
[survival.jar:git-Spigot-8a048fe-a022dd2]
3:48:32 AM at
net.minecraft.server.v1_9_R2.PlayerConnection.a(PlayerConnection.java:2088)
[survival.jar:git-Spigot-8a048fe-a022dd2]
3:48:32 AM at
net.minecraft.server.v1_9_R2.PacketPlayInUpdateSign.a(SourceFile:44)
[survival.jar:git-Spigot-8a048fe-a022dd2]
3:48:32 AM at
net.minecraft.server.v1_9_R2.PacketPlayInUpdateSign.a(SourceFile:10)
[survival.jar:git-Spigot-8a048fe-a022dd2]
3:48:32 AM at
net.minecraft.server.v1_9_R2.PlayerConnectionUtils$1.run(SourceFile:13)
[survival.jar:git-Spigot-8a048fe-a022dd2]
3:48:32 AM at java.util.concurrent.Executors$RunnableAdapter.call(Unknown
Source) [?:1.8.0_91]
3:48:32 AM at java.util.concurrent.FutureTask.run(Unknown Source)
[?:1.8.0_91]
3:48:33 AM at net.minecraft.server.v1_9_R2.SystemUtils.a(SourceFile:45)
[survival.jar:git-Spigot-8a048fe-a022dd2]
3:48:33 AM at
net.minecraft.server.v1_9_R2.MinecraftServer.D(MinecraftServer.java:726)
[survival.jar:git-Spigot-8a048fe-a022dd2]
3:48:33 AM at
net.minecraft.server.v1_9_R2.DedicatedServer.D(DedicatedServer.java:399)
[survival.jar:git-Spigot-8a048fe-a022dd2]
3:48:33 AM at
net.minecraft.server.v1_9_R2.MinecraftServer.C(MinecraftServer.java:665)
[survival.jar:git-Spigot-8a048fe-a022dd2]
3:48:33 AM at
net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:564)
[survival.jar:git-Spigot-8a048fe-a022dd2]
3:48:33 AM at java.lang.Thread.run(Unknown Source) [?:1.8.0_91]
3:48:33 AM Caused by: java.lang.NullPointerException
3:48:33 AM at
one.lindegaard.MobHunting.npc.MasterMobHunterSign.onSignChangeEvent(MasterMobHunterSign.java:318)
~[?:?]
3:48:33 AM at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
~[?:1.8.0_91]
3:48:33 AM at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
~[?:1.8.0_91]
3:48:33 AM at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown
Source) ~[?:1.8.0_91]
3:48:33 AM at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_91]
3:48:33 AM at
org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306)
~[survival.jar:git-Spigot-8a048fe-a022dd2]
3:48:33 AM ... 15 more

**Comment by Rocologo** [comment] 2016-06-02 22:08
You mean all three on the same line one one sign? 

I have not imagined that anyone would do that ☺ I will see how i can solve that ....

**Comment by silverkin** [comment] 2016-06-03 06:14
no not all three in 1 sign , i mean i try to make 3 sign with [MH1] for 1st
sign [MH2] for 2nd sign .... and i got that error message

**Comment by Rocologo** [comment] 2016-06-03 09:10
Fixed in V3.1.5.

**Closed by Rocologo** 2016-06-03 09:10 UTC

**Comment by silverkin** [comment] 2016-06-04 01:28
Problem Solved! Thank you very much :)


​

**Comment by silverkin** [comment] 2016-06-06 17:02
how to update your plugin without deleting the folder and the jar file for
mob hunting in plugin? because i tried to type /mh update then restart my
server still the old version remain.

**Comment by Rocologo** [comment] 2016-06-06 17:58
Please stop writing in the old issue ☺

**Comment by Rocologo** [comment] 2016-06-06 17:58
are you using windows or linux?

**Comment by silverkin** [comment] 2016-06-07 08:50
oh sorry, it ok now i solved the problem.. im really sorry :) i just rply
to this email because im using my smart phone sometimes
 then it's easy to access :)
