### ISSUE TITLE
Spam in console Name change detected

### ISSUE THREAD

**Issue by FlashLight34** [Rocologo/MobHunting#64] opened 2016-06-29 23:17 UTC
Mobunting 3.2.4
[01:01:22 INFO]: Ophionee issued server command: /back
[01:03:47 WARN]: [MobHunting] [MobHunting] Name change detected(2): TheMasterYonda -› Yonda_Sama UUID=3320c295-325e-4abd-a3a6-11da165d14e0
[01:03:47 WARN]: [MobHunting] [MobHunting] Name change detected(2): TheMasterYonda -› Yonda_Sama UUID=3320c295-325e-4abd-a3a6-11da165d14e0
[01:03:47 WARN]: [MobHunting] [MobHunting] Name change detected(2): TheMasterYonda -› Yonda_Sama UUID=3320c295-325e-4abd-a3a6-11da165d14e0
[01:03:47 WARN]: [MobHunting] [MobHunting] Name change detected(2): TheMasterYonda -› Yonda_Sama UUID=3320c295-325e-4abd-a3a6-11da165d14e0
[01:03:47 WARN]: [MobHunting] [MobHunting] Name change detected(2): TheMasterYonda -› Yonda_Sama UUID=3320c295-325e-4abd-a3a6-11da165d14e0
[01:03:47 WARN]: [MobHunting] [MobHunting] Name change detected(2): TheMasterYonda -› Yonda_Sama UUID=3320c295-325e-4abd-a3a6-11da165d14e0
[01:03:47 WARN]: [MobHunting] [MobHunting] Name change detected(2): TheMasterYonda -› Yonda_Sama UUID=3320c295-325e-4abd-a3a6-11da165d14e0
[01:03:47 WARN]: [MobHunting] [MobHunting] Name change detected(2): TheMasterYonda -› Yonda_Sama UUID=3320c295-325e-4abd-a3a6-11da165d14e0
[01:03:47 WARN]: [MobHunting] [MobHunting] Name change detected(2): TheMasterYonda -› Yonda_Sama UUID=3320c295-325e-4abd-a3a6-11da165d14e0
[01:03:47 WARN]: [MobHunting] [MobHunting] Name change detected(2): TheMasterYonda -› Yonda_Sama UUID=3320c295-325e-4abd-a3a6-11da165d14e0
[01:03:47 WARN]: [MobHunting] [MobHunting] Name change detected(2): TheMasterYonda -› Yonda_Sama UUID=3320c295-325e-4abd-a3a6-11da165d14e0
[01:03:47 WARN]: [MobHunting] [MobHunting] Name change detected(2): TheMasterYonda -› Yonda_Sama UUID=3320c295-325e-4abd-a3a6-11da165d14e0
[01:03:47 WARN]: [MobHunting] [MobHunting] Name change detected(2): TheMasterYonda -› Yonda_Sama UUID=3320c295-325e-4abd-a3a6-11da165d14e0
[01:03:47 WARN]: [MobHunting] [MobHunting] Name change detected(2): TheMasterYonda -› Yonda_Sama UUID=3320c295-325e-4abd-a3a6-11da165d14e0
[01:03:47 WARN]: [MobHunting] [MobHunting] Name change detected(2): TheMasterYonda -› Yonda_Sama UUID=3320c295-325e-4abd-a3a6-11da165d14e0
[01:03:47 WARN]: [MobHunting] [MobHunting] Name change detected(2): TheMasterYonda -› Yonda_Sama UUID=3320c295-325e-4abd-a3a6-11da165d14e0
[01:03:47 WARN]: [MobHunting] [MobHunting] Name change detected(2): TheMasterYonda -› Yonda_Sama UUID=3320c295-325e-4abd-a3a6-11da165d14e0
[01:03:47 WARN]: [MobHunting] [MobHunting] Name change detected(2): TheMasterYonda -› Yonda_Sama UUID=3320c295-325e-4abd-a3a6-11da165d14e0
[01:03:47 WARN]: [MobHunting] [MobHunting] Name change detected(2): TheMasterYonda -› Yonda_Sama UUID=3320c295-325e-4abd-a3a6-11da165d14e0
[01:03:47 WARN]: [MobHunting] [MobHunting] Name change detected(2): TheMasterYonda -› Yonda_Sama UUID=3320c295-325e-4abd-a3a6-11da165d14e0
[01:03:47 WARN]: [MobHunting] [MobHunting] Name change detected(2): TheMasterYonda -› Yonda_Sama UUID=3320c295-325e-4abd-a3a6-11da165d14e0
[01:03:47 WARN]: [MobHunting] [MobHunting] Name change detected(2): TheMasterYonda -› Yonda_Sama UUID=3320c295-325e-4abd-a3a6-11da165d14e0
[01:03:47 WARN]: [MobHunting] [MobHunting] Name change detected(2): TheMasterYonda -› Yonda_Sama UUID=3320c295-325e-4abd-a3a6-11da165d14e0
[01:03:47 WARN]: [MobHunting] [MobHunting] Name change detected(2): TheMasterYonda -› Yonda_Sama UUID=3320c295-325e-4abd-a3a6-11da165d14e0
[01:03:47 WARN]: [MobHunting] [MobHunting] Name change detected(2): TheMasterYonda -› Yonda_Sama UUID=3320c295-325e-4abd-a3a6-11da165d14e0
[01:03:47 WARN]: [MobHunting] [MobHunting] Name change detected(2): TheMasterYonda -› Yonda_Sama UUID=3320c295-325e-4abd-a3a6-11da165d14e0
[01:03:47 WARN]: [MobHunting] [MobHunting] Name change detected(2): TheMasterYonda -› Yonda_Sama UUID=3320c295-325e-4abd-a3a6-11da165d14e0
[01:03:47 WARN]: [MobHunting] [MobHunting] Name change detected(2): TheMasterYonda -› Yonda_Sama UUID=3320c295-325e-4abd-a3a6-11da165d14e0
[01:03:47 WARN]: [MobHunting] [MobHunting] Name change detected(2): TheMasterYonda -› Yonda_Sama UUID=3320c295-325e-4abd-a3a6-11da165d14e0
[01:03:47 WARN]: [MobHunting] [MobHunting] Name change detected(2): TheMasterYonda -› Yonda_Sama UUID=3320c295-325e-4abd-a3a6-11da165d14e0
[01:03:47 WARN]: [MobHunting] [MobHunting] Name change detected(2): TheMasterYonda -› Yonda_Sama UUID=3320c295-325e-4abd-a3a6-11da165d14e0
[01:03:47 WARN]: [MobHunting] [MobHunting] Name change detected(2): TheMasterYonda -› Yonda_Sama UUID=3320c295-325e-4abd-a3a6-11da165d14e0
[01:03:47 WARN]: [MobHunting] [MobHunting] Name change detected(2): TheMasterYonda -› Yonda_Sama UUID=3320c295-325e-4abd-a3a6-11da165d14e0
[01:03:47 WARN]: [MobHunting] [MobHunting] Name change detected(2): TheMasterYonda -› Yonda_Sama UUID=3320c295-325e-4abd-a3a6-11da165d14e0
[01:03:47 WARN]: [MobHunting] [MobHunting] Name change detected(2): TheMasterYonda -› Yonda_Sama UUID=3320c295-325e-4abd-a3a6-11da165d14e0
[01:03:47 WARN]: [MobHunting] [MobHunting] Name change detected(2): TheMasterYonda -› Yonda_Sama UUID=3320c295-325e-4abd-a3a6-11da165d14e0
[01:03:47 WARN]: [MobHunting] [MobHunting] Name change detected(2): TheMasterYonda -› Yonda_Sama UUID=3320c295-325e-4abd-a3a6-11da165d14e0
[01:03:47 WARN]: [MobHunting] [MobHunting] Name change detected(2): TheMasterYonda -› Yonda_Sama UUID=3320c295-325e-4abd-a3a6-11da165d14e0
[01:03:47 WARN]: [MobHunting] [MobHunting] Name change detected(2): TheMasterYonda -› Yonda_Sama UUID=3320c295-325e-4abd-a3a6-11da165d14e0
[01:03:47 WARN]: [MobHunting] [MobHunting] Name change detected(2): TheMasterYonda -› Yonda_Sama UUID=3320c295-325e-4abd-a3a6-11da165d14e0
[01:03:47 WARN]: [MobHunting] [MobHunting] Name 

change detected(2): TheMasterYonda -› Yonda_Sama UUID=3320c295-325e-4abd-a3a6-11da165d14e0
[01:03:47 WARN]: [MobHunting] [MobHunting] Name change detected(2): TheMasterYonda -› Yonda_Sama UUID=3320c295-325e-4abd-a3a6-11da165d14e0
[01:03:47 WARN]: [MobHunting] [MobHunting] Name change detected(2): TheMasterYonda -› Yonda_Sama UUID=3320c295-325e-4abd-a3a6-11da165d14e0
[01:03:47 WARN]: [MobHunting] [MobHunting] Name change detected(2): TheMasterYonda -› Yonda_Sama UUID=3320c295-325e-4abd-a3a6-11da165d14e0
[01:03:47 WARN]: [MobHunting] [MobHunting] Name change detected(2): TheMasterYonda -› Yonda_Sama UUID=3320c295-325e-4abd-a3a6-11da165d14e0
[01:03:47 WARN]: [MobHunting] [MobHunting] Name change detected(2): TheMasterYonda -› Yonda_Sama UUID=3320c295-325e-4abd-a3a6-11da165d14e0
[01:03:47 WARN]: [MobHunting] [MobHunting] Name change detected(2): TheMasterYonda -› Yonda_Sama UUID=3320c295-325e-4abd-a3a6-11da165d14e0
[01:03:47 WARN]: [MobHunting] [MobHunting] Name change detected(2): TheMasterYonda -› Yonda_Sama UUID=3320c295-325e-4abd-a3a6-11da165d14e0
[01:03:47 WARN]: [MobHunting] [MobHunting] Name change detected(2): TheMasterYonda -› Yonda_Sama UUID=3320c295-325e-4abd-a3a6-11da165d14e0
[01:03:47 WARN]: [MobHunting] [MobHunting] Name change detected(2): TheMasterYonda -› Yonda_Sama UUID=3320c295-325e-4abd-a3a6-11da165d14e0
[01:03:47 WARN]: [MobHunting] [MobHunting] Name change detected(2): TheMasterYonda -› Yonda_Sama UUID=3320c295-325e-4abd-a3a6-11da165d14e0
[01:03:47 WARN]: [MobHunting] [MobHunting] Name change detected(2): TheMasterYonda -› Yonda_Sama UUID=3320c295-325e-4abd-a3a6-11da165d14e0
[01:03:47 WARN]: [MobHunting] [MobHunting] Name change detected(2): TheMasterYonda -› Yonda_Sama UUID=3320c295-325e-4abd-a3a6-11da165d14e0
[01:03:47 WARN]: [MobHunting] [MobHunting] Name change detected(2): TheMasterYonda -› Yonda_Sama UUID=3320c295-325e-4abd-a3a6-11da165d14e0
[01:03:47 WARN]: [MobHunting] [MobHunting] Name change detected(2): TheMasterYonda -› Yonda_Sama UUID=3320c295-325e-4abd-a3a6-11da165d14e0
[01:03:47 WARN]: [MobHunting] [MobHunting] Name change detected(2): TheMasterYonda -› Yonda_Sama UUID=3320c295-325e-4abd-a3a6-11da165d14e0
[01:03:47 WARN]: [MobHunting] [MobHunting] Name change detected(2): TheMasterYonda -› Yonda_Sama UUID=3320c295-325e-4abd-a3a6-11da165d14e0
[01:03:47 WARN]: [MobHunting] [MobHunting] Name change detected(2): TheMasterYonda -› Yonda_Sama UUID=3320c295-325e-4abd-a3a6-11da165d14e0
[01:03:47 WARN]: [MobHunting] [MobHunting] Name change detected(2): TheMasterYonda -› Yonda_Sama UUID=3320c295-325e-4abd-a3a6-11da165d14e0
[01:03:47 WARN]: [MobHunting] [MobHunting] Name change detected(2): TheMasterYonda -› Yonda_Sama UUID=3320c295-325e-4abd-a3a6-11da165d14e0
[01:03:47 WARN]: [MobHunting] [MobHunting] Name change detected(2): TheMasterYonda -› Yonda_Sama UUID=3320c295-325e-4abd-a3a6-11da165d14e0
[01:03:47 WARN]: [MobHunting] [MobHunting] Name change detected(2): TheMasterYonda -› Yonda_Sama UUID=3320c295-325e-4abd-a3a6-11da165d14e0
[01:03:47 WARN]: [MobHunting] [MobHunting] Name change detected(2): TheMasterYonda -› Yonda_Sama UUID=3320c295-325e-4abd-a3a6-11da165d14e0
[01:03:47 WARN]: [MobHunting] [MobHunting] Name change detected(2): TheMasterYonda -› Yonda_Sama UUID=3320c295-325e-4abd-a3a6-11da165d14e0
[01:03:47 WARN]: [MobHunting] [MobHunting] Name change detected(2): TheMasterYonda -› Yonda_Sama UUID=3320c295-325e-4abd-a3a6-11da165d14e0
[01:03:47 WARN]: [MobHunting] [MobHunting] Name change detected(2): TheMasterYonda -› Yonda_Sama UUID=3320c295-325e-4abd-a3a6-11da165d14e0
[01:03:47 WARN]: [MobHunting] [MobHunting] Name change detected(2): TheMasterYonda -› Yonda_Sama UUID=3320c295-325e-4abd-a3a6-11da165d14e0
[01:03:47 WARN]: [MobHunting] [MobHunting] Name change detected(2): TheMasterYonda -› Yonda_Sama UUID=3320c295-325e-4abd-a3a6-11da165d14e0
[01:03:47 WARN]: [MobHunting] [MobHunting] Name change detected(2): TheMasterYonda -› Yonda_Sama UUID=3320c295-325e-4abd-a3a6-11da165d14e0
[01:03:47 WARN]: [MobHunting] [MobHunting] Name change detected(2): TheMasterYonda -› Yonda_Sama UUID=3320c295-325e-4abd-a3a6-11da165d14e0
[01:03:47 WARN]: [MobHunting] [MobHunting] Name change detected(2): TheMasterYonda -› Yonda_Sama UUID=3320c295-325e-4abd-a3a6-11da165d14e0
[01:03:47 WARN]: [MobHunting] [MobHunting] Name change detected(2): TheMasterYonda -› Yonda_Sama UUID=3320c295-325e-4abd-a3a6-11da165d14e0
[01:03:47 WARN]: [MobHunting] [MobHunting] Name change detected(2): TheMasterYonda -› Yonda_Sama UUID=3320c295-325e-4abd-a3a6-11da165d14e0
[01:03:47 WARN]: [MobHunting] [MobHunting] Name change detected(2): TheMasterYonda -› Yonda_Sama UUID=3320c295-325e-4abd-a3a6-11da165d14e0
[01:03:47 WARN]: [MobHunting] [MobHunting] Name change detected(2): TheMasterYonda -› Yonda_Sama UUID=3320c295-325e-4abd-a3a6-11da165d14e0
[01:03:47 WARN]: [MobHunting] [MobHunting] Name change detected(2): TheMasterYonda -› Yonda_Sama UUID=3320c295-325e-4abd-a3a6-11da165d14e0
[01:03:47 WARN]: [MobHunting] [MobHunting] Name change detected(2): TheMasterYonda -› Yonda_Sama UUID=3320c295-325e-4abd-a3a6-11da165d14e0
[01:03:47 WARN]: [MobHunting] [MobHunting] Name change detected(2): TheMasterYonda -› Yonda_Sama UUID=3320c295-325e-4abd-a3a6-11da165d14e0
[01:03:47 WARN]: [MobHunting] [MobHunting] Name change detected(2): TheMasterYonda -› Yonda_Sama UUID=3320c295-325e-4abd-a3a6-11da165d14e0
[01:03:47 WARN]: [MobHunting] [MobHunting] Name change detected(2): TheMasterYonda -› Yonda_Sama UUID=3320c295-325e-4abd-a3a6-11da165d14e0
[01:03:47 WARN]: [MobHunting] [MobHunting] Name change detected(2): TheMasterYonda -› Yonda_Sama UUID=3320c295-325e-4abd-a3a6-11da165d14e0
[01:03:47 WARN]: [MobHunting] [MobHunting] Name change detected(2): TheMasterYonda -› Yonda_Sama UUID=3320c295-325e-4abd-a3a6-11da165d14e0
[01:03:47 WARN]: [MobHunting] [MobHunting] Name change detected(2): TheMasterYonda -› Yonda_Sama UUID=3320c295-325e-4abd-a3a6-11da165d14e0
[01:03:47 WARN]: [MobHunting] [MobHunting] Name change detected(2): TheMasterYonda -› Yonda_Sama UUID=3320c295-325e-4abd-a3a6-11da165d14e0
[01:03:47 WARN]: [MobHunting] [MobHunting] Name change detected(2): TheMasterYonda -› Yonda_Sama UUID=3320c295-325e-4abd-a3a6-11da165d14e0
[01:04:30 INFO]: UUID of player masca4 is dc7d3e6f-4544-4da9-bd6a-d0c44647552d
[01:04:30 INFO]: [Setrankmod]  Â§9â Â§7masca4 Â§9se connecte a Worldust...
[01:04:30 INFO]: [Setrankmod] SafeUnderground Teste Its SAFE! masca4 in world worldust2
[01:04:30 INFO]: masca4[/92.132.95.27:51128] logged in with entity id 2682254 at ([worldust2]-541.190604767663, 51.0, -2949.913333300091)
[01:04:45 INFO]: [FD] Ophionee -› 1 Emeraude worldust2 [XLvl:430~Ores:1] (loc: -725.1707532984317 24.0 473.69999998807907)
[01:08:47 WARN]: [MobHunting] [MobHunting] Name change detected(2): TheMasterYonda -› Yonda_Sama UUID=3320c295-325e-4abd-a3a6-11da165d14e0
[01:08:47 WARN]: [MobHunting] [MobHunting] Name change detected(2): TheMasterYonda -› Yonda_Sama UUID=3320c295-325e-4abd-a3a6-11da165d14e0
[01:08:47 WARN]: [MobHunting] [MobHunting] Name change detected(2): TheMasterYonda -› Yonda_Sama UUID=3320c295-325e-4abd-a3a6-11da165d14e0
[01:08:47 WARN]: [MobHunting] [MobHunting] Name change detected(2): TheMasterYonda -› Yonda_Sama UUID=3320c295-325e-4abd-a3a6-11da165d14e0
[01:08:47 WARN]: [MobHunting] [MobHunting] Name change detected(2): TheMasterYonda -› Yonda_Sama UUID=3320c295-325e-4abd-a3a6-11da165d14e0
[01:08:47 WARN]: [MobHunting] [MobHunting] Name change detected(2): TheMasterYonda -› Yonda_Sama UUID=3320c295-325e-4abd-a3a6-11da165d14e0
[01:08:47 WARN]: [MobHunting] [MobHunting] Name change detected(2): TheMasterYonda -› Yonda_Sama UUID=3320c295-325e-4abd-a3a6-11da165d14e0
[01:08:47 WARN]: [MobHunting] [MobHunting] Name change detected(2): TheMasterYonda -› Yonda_Sama UUID=3320c295-325e-4abd-a3a6-11da165d14e0
[01:08:47 WARN]: [MobHunting] [MobHunting] Name change detected(2): TheMasterYonda -› Yonda_Sama UUID=3320c295-325e-4abd-a3a6-11da165d14e0
[01:08:47 WARN]: [MobHunting] [MobHunting] Name change detected(2): TheMasterYonda -› Yonda_Sama UUID=3320c295-325e-4abd-a3a6-11da165d14e0
[01:15:21 INFO]: Ophionee issued server command: /back

**Comment by Rocologo** [comment] 2016-06-30 05:37
Please check the log file for any errors before the spam.

I cant remember if you use mysql or sqlite?

**Comment by FlashLight34** [comment] 2016-06-30 11:36
sqlite

**Comment by Rocologo** [comment] 2016-06-30 20:31
Please check your console log for errors or other info, before this happened.

**Comment by FlashLight34** [comment] 2016-06-30 23:23
i only see that

[10:21:49] [User Authenticator #13/INFO]: UUID of player Yonda_Sama is 3320c295-325e-4abd-a3a6-11da165d14e0
[10:21:49] [MH TaskThread/WARN]: [MobHunting] [MobHunting] Name change detected(2): TheMasterYonda -> Yonda_Sama UUID=3320c295-325e-4abd-a3a6-11da165d14e0
[10:21:49] [Server thread/INFO]: [Setrankmod]  §9✔ §8Yonda_Sama §9se connecte a Worldust...
[10:21:49] [Server thread/INFO]: [Setrankmod] SafeUnderground Teste Its SAFE! Yonda_Sama in world worldust2
[10:21:49] [MH TaskThread/WARN]: [MobHunting] [MobHunting] Name change detected(2): TheMasterYonda -> Yonda_Sama UUID=3320c295-325e-4abd-a3a6-11da165d14e0
[10:21:49] [Server thread/INFO]: Yonda_Sama[/85.201.248.224:53504] logged in with entity id 239876 at ([worldust2]-890.3000000119209, 82.0, -3262.5506446526188)

and

[10:30:48] [Server thread/ERROR]: Could not pass event PlayerDeathEvent to MobHunting v3.2.4
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.9.4.jar:git-Spigot-798f32d-0cd0397]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.9.4.jar:git-Spigot-798f32d-0cd0397]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.9.4.jar:git-Spigot-798f32d-0cd0397]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.9.4.jar:git-Spigot-798f32d-0cd0397]
	at org.bukkit.craftbukkit.v1_9_R2.event.CraftEventFactory.callPlayerDeathEvent(CraftEventFactory.java:409) [spigot-1.9.4.jar:git-Spigot-798f32d-0cd0397]
	at net.minecraft.server.v1_9_R2.EntityPlayer.die(EntityPlayer.java:404) [spigot-1.9.4.jar:git-Spigot-798f32d-0cd0397]
	at net.minecraft.server.v1_9_R2.EntityLiving.damageEntity(EntityLiving.java:903) [spigot-1.9.4.jar:git-Spigot-798f32d-0cd0397]
	at net.minecraft.server.v1_9_R2.EntityHuman.damageEntity(EntityHuman.java:766) [spigot-1.9.4.jar:git-Spigot-798f32d-0cd0397]
	at net.minecraft.server.v1_9_R2.EntityPlayer.damageEntity(EntityPlayer.java:495) [spigot-1.9.4.jar:git-Spigot-798f32d-0cd0397]
	at net.minecraft.server.v1_9_R2.MobEffectList.tick(MobEffectList.java:66) [spigot-1.9.4.jar:git-Spigot-798f32d-0cd0397]
	at net.minecraft.server.v1_9_R2.MobEffect.b(SourceFile:111) [spigot-1.9.4.jar:git-Spigot-798f32d-0cd0397]
	at net.minecraft.server.v1_9_R2.MobEffect.tick(SourceFile:98) [spigot-1.9.4.jar:git-Spigot-798f32d-0cd0397]
	at net.minecraft.server.v1_9_R2.EntityLiving.tickPotionEffects(EntityLiving.java:525) [spigot-1.9.4.jar:git-Spigot-798f32d-0cd0397]
	at net.minecraft.server.v1_9_R2.EntityLiving.U(EntityLiving.java:284) [spigot-1.9.4.jar:git-Spigot-798f32d-0cd0397]
	at net.minecraft.server.v1_9_R2.Entity.m(Entity.java:301) [spigot-1.9.4.jar:git-Spigot-798f32d-0cd0397]
	at net.minecraft.server.v1_9_R2.EntityLiving.m(EntityLiving.java:1711) [spigot-1.9.4.jar:git-Spigot-798f32d-0cd0397]
	at net.minecraft.server.v1_9_R2.EntityHuman.m(EntityHuman.java:143) [spigot-1.9.4.jar:git-Spigot-798f32d-0cd0397]
	at net.minecraft.server.v1_9_R2.EntityPlayer.k_(EntityPlayer.java:242) [spigot-1.9.4.jar:git-Spigot-798f32d-0cd0397]
	at net.minecraft.server.v1_9_R2.PlayerConnection.c(PlayerConnection.java:138) [spigot-1.9.4.jar:git-Spigot-798f32d-0cd0397]
	at net.minecraft.server.v1_9_R2.NetworkManager.a(NetworkManager.java:233) [spigot-1.9.4.jar:git-Spigot-798f32d-0cd0397]
	at net.minecraft.server.v1_9_R2.ServerConnection.c(ServerConnection.java:140) [spigot-1.9.4.jar:git-Spigot-798f32d-0cd0397]
	at net.minecraft.server.v1_9_R2.MinecraftServer.D(MinecraftServer.java:825) [spigot-1.9.4.jar:git-Spigot-798f32d-0cd0397]
	at net.minecraft.server.v1_9_R2.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.9.4.jar:git-Spigot-798f32d-0cd0397]
	at net.minecraft.server.v1_9_R2.MinecraftServer.C(MinecraftServer.java:665) [spigot-1.9.4.jar:git-Spigot-798f32d-0cd0397]
	at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:564) [spigot-1.9.4.jar:git-Spigot-798f32d-0cd0397]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45-internal]
Caused by: java.lang.ClassCastException: org.bukkit.event.entity.EntityDamageEvent cannot be cast to org.bukkit.event.entity.EntityDamageByEntityEvent
	at one.lindegaard.MobHunting.MobHunting.onPlayerDeath(MobHunting.java:516) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_45-internal]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_45-internal]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_45-internal]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_45-internal]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.9.4.jar:git-Spigot-798f32d-0cd0397]
	... 25 more

**Comment by Rocologo** [comment] 2016-07-01 05:42
This might actually be the root cause of this error. I will fix it today a then we see if it removes then spam on next player who changes name.

**Comment by Rocologo** [comment] 2016-07-01 11:53
Both errors is fixed in V3.2.6

**Closed by Rocologo** 2016-07-01 11:53 UTC
Labels: bug
