### ISSUE TITLE
MyPet Error

### ISSUE THREAD

**Issue by Sikatsu** [Rocologo/MobHunting#210] opened 2017-04-06 13:38 UTC
Error: https://pastebin.com/B83qwXZt

**Comment by Rocologo** [comment] 2017-04-06 17:43
I need ALL the lines including the ones after "INFO Caused by: java.lang.NullPointerException" the last lines contain the linenumbers in my code where the plugin failed, so I am missing the most important part :-)

**Comment by Rocologo** [comment] 2017-04-09 06:28
what version of MyPet do you use?

**Comment by Rocologo** [comment] 2017-04-09 06:33
Same bug https://github.com/Rocologo/MobHunting/issues/214

**Comment by Sikatsu** [comment] 2017-04-09 11:32
Whoops, I didn't see the message from 3 days ago. Didn't see the error anymore ever since..

**Comment by Rocologo** [comment] 2017-04-10 17:35
I don't have access to MyPet Premium 2.3.4. I can only test with 2.2.9 & 2.3.0-SNAPSHOT and I cant replicate the error.

I'm not sure the bug is because of MobHunting either. 

In fact this text line 
Caused by: java.lang.NullPointerException [12:59:45 ERROR]: Could not pass event EntityDeathEvent to MobHunting v4.7.6 org.bukkit.event.EventException at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.11.jar:git-Spigot-6f7aabf-c8ff651] at 

Indicates that the error is in spigot-1.11..jar, so I would recommend that you keep spigot upgraded.

**Comment by Sikatsu** [comment] 2017-04-11 14:13
I always run the latest spigot version, as I update nearly every night. So that shouldn't be the problem, though I didn't see the error again ever since I reported it here.

**Comment by Sikatsu** [comment] 2017-04-15 15:04
There it is, a full error log: https://pastebin.com/Q2qndEVF

**Comment by Sikatsu** [comment] 2017-04-16 22:09
This error is driving me nuts, it's getting spammed somehow these days..

**Comment by Rocologo** [comment] 2017-04-17 06:12
Thank you for the full error text. I now know where the problem is, but please enable debug and give me the the debug kill information. I can see its assisted kill, but i cant tell who is the killer and who is assister. The debug information will help me to understand this

**Comment by Sikatsu** [comment] 2017-04-17 10:35
I wasn't online at that moment, just saw the error spamming when I checked on my phone.
But I guess they are using the pet train farm with 2-3 people to train their pet.

**Comment by Sikatsu** [comment] 2017-04-17 12:26
https://pastebin.com/c3q9ct5L

**Comment by Sikatsu** [comment] 2017-04-18 18:31
My console is nothing else then this error these days lol

**Comment by Rocologo** [comment] 2017-04-18 18:44
Im sorry have been on vacation and very busy afterwards. I looked at your log, but I need the debug information before the error, from the line 

======================= new kill =========================

**Comment by Sikatsu** [comment] 2017-04-18 19:41
I understand, sorry. Just my console is becoming useless currently.

Full, extended error log: https://pastebin.com/0fp8phsj

**Comment by Rocologo** [comment] 2017-04-19 12:40
Sorry for being slow on this one.... but I finally found some time for doing some development :-)

please test build 345 or newer:

https://fractal.lindegaard.one:8181/job/MobHunting

**Comment by Sikatsu** [comment] 2017-04-19 13:13
Thanks, on peak right now so I can't test earlier then this evening.

**Comment by Sikatsu** [comment] 2017-04-19 22:31
Not fixed. Error has changed though: https://pastebin.com/vZdqFkJ1

**Comment by Sikatsu** [comment] 2017-04-20 19:00
Referanced this issue, but not fixed I suppose? @Rocologo

**Comment by Rocologo** [comment] 2017-04-20 19:15
You were a bit too fast :-) 

I hope it is fixed now in build 348, Im testing in this moment, to see if I can find more bugs.

**Comment by Sikatsu** [comment] 2017-04-20 19:32
Oh haha! Gonna test it now aswell.

**Comment by Sikatsu** [comment] 2017-04-20 19:57
Not fixed it seems.

**Comment by Sikatsu** [comment] 2017-04-20 19:57
https://pastebin.com/AhbqAU7S

**Comment by Rocologo** [comment] 2017-04-20 21:17
:-( sorry for these annoying bugs :-( Thank you for you patience!!! The debug information helped me.

Its VERY hard to test all aspects of this plugin. There are so many many combinations because of all the integrations I have made. In this case it was some kind of assisted kill - where MyPet was the killer and the player was the assister.... i think :-)

Anyway please try build 349
https://fractal.lindegaard.one:8181/job/MobHunting/

**Comment by Sikatsu** [comment] 2017-04-20 21:19
That's fine! Hopefully we can get it fixed.

Hmm, as the MyPet is on ''Farm'' mode, all Eroxx99 and I were doing is flying afk in the air while our pets are killing mobs. We didn't hit the mobs at all. Let me test the new version now.

**Comment by Rocologo** [comment] 2017-04-20 21:22
Okay, if the bug is not solved now, then I will try to put MyPet into Farm and fly AFK like you did, so reproduce the bug. 

Another thing: You could argue that you should not get rewards at all, when you were flying AFK. The rules is usually No Risk - No Money :-) What do you think?

**Comment by Rocologo** [comment] 2017-04-20 21:23
I have to go to bed now. If the bug is solved, I will make an release in the morning.

**Comment by Sikatsu** [comment] 2017-04-20 21:25
Agree, but it's just for pet training. Actually mobhunting isn't doing anything except for giving these errors.
Gonna test the new version now! Will let you know in a moment, goodnight!

**Comment by Sikatsu** [comment] 2017-04-20 21:33
So far so good, didn't see the error yet. Though sometimes money is dropping. We are in fly and not hitting mobs. (http://prntscr.com/eyw16b)

**Comment by Rocologo** [comment] 2017-04-20 21:46
I think you wil get a half reward when your pet is killing mobs also when you dont hit the mob, unless assist is disabled in config.yml 

It the rewards drop close they will merge into one item and the values will be added.

**Comment by Sikatsu** [comment] 2017-04-20 21:47
I see, but they are mobs from a mobspawner. So money shouldn't drop at all, atleast that's how I've set it up.

So far so good, still.

**Comment by Rocologo** [comment] 2017-04-21 13:03
I have released V4.7.8

**Comment by Sikatsu** [comment] 2017-04-24 10:34
@Rocologo Oh come on... I just woke up and it's spamming again!

Error: https://pastebin.com/DLmEgqEf

**Comment by Rocologo** [comment] 2017-04-24 16:54
I found the bug. Please test build 354

https://fractal.lindegaard.one:8181/job/MobHunting/

**Comment by Rocologo** [comment] 2017-04-24 17:37
hmm. its not fixed yet.

**Comment by Sikatsu** [comment] 2017-04-24 17:43
I honestly don't know how to reproduce it this time, but earlier today it kept on spamming.

**Comment by Sikatsu** [comment] 2017-04-24 17:46
Nevermind, it still spams.

https://pastebin.com/RdyX7suR

**Comment by Rocologo** [comment] 2017-04-24 17:57
I know how to, its when the Pet is farmning. (when the the pet kills a mob without the player hitting on the mob) Im close solve the issue.

**Comment by Rocologo** [comment] 2017-04-24 18:52
I think I got it this time. Please try build 355 https://fractal.lindegaard.one:8181/job/MobHunting/

**Closed** 2017-04-25 11:40 UTC

**Comment by Sikatsu** [comment] 2017-04-25 12:48
So far so good.
