### ISSUE TITLE
Can't get mobhunting heads off my head

### ISSUE THREAD

**Issue by Sikatsu** [Rocologo/MobHunting#670] opened 2020-07-18 12:25 UTC
When a player puts a mobhunting head on his head, he is unable to get it off. It seems like there is some sort of curse of binding enchant on it somehow.

**Comment by Rocologo** [comment] 2020-07-18 23:25
You can use essentials /hat remove

But the bug is fixed in 7.5.1, so players cant move the bag to the head using shift + click

**Comment by Sikatsu** [comment] 2020-07-19 11:24
I don't use essentials haha, but thanks for fixing it!

**Comment by Rocologo** [comment] 2020-07-19 11:26
Okay, but I dont know how to removed the head without Essentials ? I hope you have found a way then.

**Comment by Sikatsu** [comment] 2020-07-19 12:49
Well dying worked haha ^^

I have to see with the new update if this is fixed!

**Comment by Sikatsu** [comment] 2020-07-19 16:02
![image](https://user-images.githubusercontent.com/5664135/87879291-0d3f3d80-c9ea-11ea-9314-801c149fc7d9.png)
Can just put it on my head, I either drag it or shift + click..

**Comment by Rocologo** [comment] 2020-07-19 16:04
What??  I know I tested without BagOfGold

**Comment by Sikatsu** [comment] 2020-07-19 16:09
I mean, I thought I had a bypass so even deopped and set myself to a player rank, but I can just do it. o.O

**Comment by Sikatsu** [comment] 2020-07-19 16:10
I spawned a head in with /mh head give Sikatsu pufferfish

Since the player that reported it also had a pufferfish head.

**Comment by Rocologo** [comment] 2020-07-19 16:39
I can reproduce this???? Very odd....

**Comment by Rocologo** [comment] 2020-07-19 16:40
CAN'T reproduce :-(

**Comment by Sikatsu** [comment] 2020-07-19 16:45
That is really odd, what am I doing differently?

**Comment by Rocologo** [comment] 2020-07-19 16:57
Yes tell me :-D

I have tried i both creative and survival and from both player inventory and from the hotbar. With both normal moving with the mouse and with shift-click.

**Comment by Rocologo** [comment] 2020-07-19 16:57
All combinations

**Comment by Sikatsu** [comment] 2020-07-19 17:09
It's not just me, everyone is just able to put it on their head :(

**Comment by Rocologo** [comment] 2020-07-19 17:17
No worries I believe you can do it. I think we have to look after differences between our servers. Plugins and so.

**Comment by Rocologo** [comment] 2020-07-19 17:17
But this it suddenly a hard one to solve :-(

**Comment by Sikatsu** [comment] 2020-07-19 17:19
Surprised if it would be a plugin conflict actually. I am running build 101 of paper.

![image](https://user-images.githubusercontent.com/5664135/87880774-bbe87b80-c9f4-11ea-9f4a-e0b20e709aa8.png)

**Comment by Rocologo** [comment] 2020-07-19 17:37
Im running SpigotMC 

Hmm

**Comment by Rocologo** [comment] 2020-07-19 17:39
I will try to install HeadDatabase

**Comment by Sikatsu** [comment] 2020-07-19 18:18
Doubt it is a plugin conflict..

**Comment by Sikatsu** [comment] 2020-07-20 20:53
@Rocologo Indeed, this is a weird issue. For me I can not reproduce it for the life of me, but players definitely have this issue. 

A player made a video of it. 

https://www.dropbox.com/s/9vk3jz24xemogzt/Minecraft_%201.16.1%20-%20Multiplayer%20%283rd-party%20Server%29%202020-07-20%2022-47-41.mp4?dl=0

**Comment by Sikatsu** [comment] 2020-07-20 20:54
Players also mention this doesn't happen ALWAYS, but he was able to get it to work the first time I asked to reproduce it...

**Comment by Sikatsu** [comment] 2020-07-20 20:56
Happens to heads with this lore
![image](https://user-images.githubusercontent.com/5664135/87985662-43f58080-cadc-11ea-9413-619a8c53e7ba.png)

Not with these 
![image](https://user-images.githubusercontent.com/5664135/87985671-48ba3480-cadc-11ea-8794-485f1cfb4f02.png)

**Comment by Sikatsu** [comment] 2020-07-25 06:48
Did you reproduce it with headdatabase installed?

**Comment by Rocologo** [comment] 2020-07-25 07:00
I only got to my computer today. I will look at this issue now.

**Comment by Rocologo** [comment] 2020-07-25 07:03
I cant get a head without the lore "MobHunting Reward" do you know how to get that one. The head might be broken, since the Lore is missing.

**Comment by Sikatsu** [comment] 2020-07-25 09:37
I think those are from minecraft itself? Not sure actually, but it happens to the one with mobhunting lore.

**Comment by Sikatsu** [comment] 2020-07-25 12:27
@Rocologo Turns out shift + click indeed blocks the head from wearing. Just dragging it the normal way still works though, and I can indeed not get the head off anymore..

![image](https://user-images.githubusercontent.com/5664135/88456961-e6b65200-ce82-11ea-8dfc-b692ba5e486b.png)

**Comment by Momshroom** [comment] 2020-07-25 13:21
Being able to wear heads is a normal Minecraft thing.   I’ve been meaning to write a bug report about the heads not staying on— you put them on and they pop back off, but had not yet tested enough to be sure which plugin caused the issue.

**Comment by Sikatsu** [comment] 2020-07-25 13:25
It is a normal thing, but with the mobhunting mobheads it's bugging out. You can get them on, but you can not get them off your head without using a command like /hat.

**Comment by Sikatsu** [comment] 2020-07-30 00:04
Any news regarding this? @Rocologo

**Comment by Sikatsu** [comment] 2020-08-06 20:49
@Rocologo Any news regarding this?

**Comment by Rocologo** [comment] 2020-08-08 17:58
Im sorry I have had very little time to take care of my plugins, but today I finally got a break through!!!

I found out how the players were able to place a head in the helmet slot! The problem was that when a player Dragged the Bag across serval slots an event called "InventoryDragEvent" was called, and I didnt know that event, so it was unhandled. This made me discover yet another unhandled event "InventoryMoveItemEvent" and these two unhandled events is the root cause to many of the bugs I have been fighting where the balance did not calculate correct. 

So now Im taking care of both these events and now both dragging and balance seems to work :-)

Please test 1073

https://fractal.lindegaard.one:8181/job/MobHunting/1073/

and let me know if you still are able to place the bag in the helmet slot. I hope not :-D

**Comment by Sikatsu** [comment] 2020-08-08 20:34
I can shift + click or drag it into the helmet slot on 1075

![image](https://user-images.githubusercontent.com/5664135/89719308-43f3ec80-d9c7-11ea-8ae3-424025186ef7.png)

**Comment by Sikatsu** [comment] 2020-08-08 21:24
Not that it's a problem, as long as you can get the head off.. that would even be better then just blocking it I guess!

**Comment by Rocologo** [comment] 2020-08-09 07:17
Ahh, but it is allowed to wear heads, but not the Bags. I think this is like Minecraft Vanilla, that you can wear heads? 

And yes, yesterday I decided that I would make it possible to remove the heads from the helmet slot - no matter it should not be possible to place the Bag in the slot. And it was actually this which made me find the "unknown" event. Because I could now "speed click" on the slot and then I discovered that I SOMETIME could place the bag in the slot, but now when i did it slowly.

So yes - I think this is fixed now. 

I will make a release now, because this is a major bug which is fixed now. (The missing event). 

Im very happy about your help and your patience. Thank You!

**Comment by Sikatsu** [comment] 2020-08-09 17:13
Is this permission based?

![image](https://user-images.githubusercontent.com/5664135/89737804-59732000-da74-11ea-99c3-0b852bca7386.png)

I can put a bag of gold on my head with shift + click or dragging..
Players can not shift + click a normal mobhunting head, it will just return to the place it was before..

**Comment by Rocologo** [comment] 2020-08-09 17:17
Please be VERY specific in what you are doing? Because i tested this today and i could not move a head into the helmet slot.

**Comment by Rocologo** [comment] 2020-08-09 17:22
And no. There is no permission

**Comment by Sikatsu** [comment] 2020-08-09 17:36
I can shift + click to get the mobhunting head OR the bag of gold in the helmet slot, as well for dragging it. 

Players can drag it into the helmet slot, but not shift + click, when they shift + click, it will move for a split second to the helmet slot and then return in the slot it was in..

**Comment by Sikatsu** [comment] 2020-08-09 17:53
Video: [Minecraft__1.16.1_-_Multiplayer_3rd-party_Server_2020-08-09_19-41-27.zip](https://github.com/Rocologo/MobHunting/files/5048165/Minecraft__1.16.1_-_Multiplayer_3rd-party_Server_2020-08-09_19-41-27.zip)

**Comment by Rocologo** [comment] 2020-08-15 21:05
This should be fixedin build 1079

https://fractal.lindegaard.one:8181/job/MobHunting/

Im sorry I did get this in to V7.5.4

**Closed by Rocologo** 2020-08-15 21:05 UTC
Labels: Fixed - To be tested

**Comment by Sikatsu** [comment] 2020-08-15 21:06
So is this now blocked, or can we just get it off like it should? haha

**Comment by Rocologo** [comment] 2020-08-15 21:10
I have tested shift+click (MOVE_TO_OTHER_INVENTORY) and I discovered that it was possible to SWAP a bag into the Helmet slot, if there was already a HEAD in the slot. 

BAGS is blocked. HEADS is not. 

I hope. :-)

**Comment by Rocologo** [comment] 2020-08-15 21:11
Im not blocking to pull off Bags :-)

**Comment by Sikatsu** [comment] 2020-08-15 21:14
Gotch'a! We don't really use bags, and heads I think were already no longer a problem. Thanks though!

Keep up the good work.
