### ISSUE TITLE
Not every fish gives money

### ISSUE THREAD

**Issue by Sikatsu** [Rocologo/MobHunting#127] opened 2017-02-05 00:07 UTC
Using 4.4.1-SNAPSHOT, not every fish that I catch gives money. (This might also apply on older versions, but now the messages are working I notice about this)

First 2 fishes didn't give money, then 3 gave money and then again a fish didn't give money. Seems to be a bit buggy.  80% of the times it works fine though.

**Comment by Rocologo** [comment] 2017-02-05 11:07
Sometimes the fish (as an item to be piucked up) is in the water instead of the inventory. I this case you will still get the reward. Try fishing on low water near by you, then you will see.

I don't have a solution for this, because you caught a fish, you just didnt got it in your inventory. I cant solve that, because the "PlayerFishEvent" does not give me the information. 

It is either Minecraft or the Bukkit API which is buggy. I cant do anything than making an report to the Spigot team.

**Comment by Sikatsu** [comment] 2017-02-05 11:42
Hmm, the item was actually in my inventory. However usually it goes into a hopper, but not this time.

**Comment by Sikatsu** [comment] 2017-02-05 12:20
But it's suppose to give the money even when the fish is not in my inventory? Then why doesn't it give cash everytime?

The fish I catched yesterday didn't give money, but it was in my inventory.

**Comment by Rocologo** [comment] 2017-02-05 18:39
The PlayerFishEvent in the Bukkit API seems very buggy and the documentation does not reflect what actually happens. It look like the PlayerFishEvent is call with wrong states. I can fix this I think it's a Minecraft / Bukkit API bug. I need time to makeep a bug report.

**Comment by Sikatsu** [comment] 2017-02-05 19:03
That's alright! It works most of the times. This is a minor bug I think.

**Comment by Sikatsu** [comment] 2017-02-09 23:00
@Rocologo This bug is getting worser or something..

**Comment by Rocologo** [comment] 2017-02-09 23:53
I will report this problem to the spigot team

**Comment by Sikatsu** [comment] 2017-02-10 00:11
Thanks, appreciated

**Comment by Rocologo** [comment] 2017-02-10 08:26
I have reported the issue
https://hub.spigotmc.org/jira/browse/SPIGOT-3059

Lets hope they can do something.

**Comment by Sikatsu** [comment] 2017-02-10 11:45
Seems he replied :)

**Comment by Sikatsu** [comment] 2017-02-10 12:26
I just tested with staff, and it happens way to often that you don't receive money for fishing. It's like 60% yes, 40%. Hope MD_5 can do something.

**Comment by Rocologo** [comment] 2017-02-10 15:03
He rejected the bug report. And asked me to provide evidence and a way to reproduce this bug.

So I am on my own again. So I have worked on it again and studied the @EventHandler and its settings.

I think it works alot better now (still not 100% perfect), and it works with mcmmo too.

Please test this one 
https://dl.dropboxusercontent.com/u/36067670/MobHunting/MobHunting-4.4.4-SNAPSHOT-Bnull.jar

My Jenkins server is down until tonight, so you have to fetch it from dropbox.

**Comment by Sikatsu** [comment] 2017-02-10 15:15
Will test! McMMO? You mean items?

**Comment by Rocologo** [comment] 2017-02-10 15:18
yes, McMMO sometimes change the caught fish to another item. I have seen TNT, RECORD, SPADE, if McMMO or anyother plugin changes the fish to something else, the player will not et a reward.

**Comment by Sikatsu** [comment] 2017-02-10 15:37
Been fishing for the past 20 minutes. I received cash for every fish, and didn't receive cash for items. Nice catch! :)

If issues occur on the main server, I will let you know, but on my test server it works fine now.

**Comment by Rocologo** [comment] 2017-02-10 15:39
On my server too :-) This one has been hard to solve :-) 

I close this now.

**Closed by Rocologo** 2017-02-10 15:39 UTC
Labels: bug

**Comment by Sikatsu** [comment] 2017-02-10 15:59
Indeed! Glad it's fixed :)
