### ISSUE TITLE
You can get Achievements where rewards are disabled

### ISSUE THREAD

**Issue by Maxetto** [Rocologo/MobHunting#44] opened 2016-05-22 13:42 UTC
I've got an achievement while I was in MobArena, nothing more to say :stuck_out_tongue:

**Comment by Rocologo** [comment] 2016-05-22 17:33
You have to help me here, I checked the code and you should now get a reward(if config.yml is configured not not to)
My code looks like this:

> 		if (killer instanceof Player) {
> 			if (MobArenaCompat.isEnabledInConfig() && MobArenaHelper.isPlayingMobArena(killer)
> 					&& !mConfig.mobarenaGetRewards) {
> 				debug("KillBlocked: %s is currently playing MobArena.", killer.getName());
> 				learn(killer, Messages.getString("mobhunting.learn.mobarena"));
> 				return;

So I would like to see your config.yml to validate the plugin behavior. Either you have set the two parm wrong or it could be that isPlayingMobArena dont catch that you are playing MobArena.

**Comment by Maxetto** [comment] 2016-05-22 18:06
I'm talking about achievements, it seems that the part of code you referenced it's just for rewards.

If it could help, the achievement I got was Creepercide (maybe it's a flaw in EntityDamageEvent instead of those with MobHuntKillEvent)

**Comment by Rocologo** [comment] 2016-05-23 03:20
Yes, I understood that ☺ Its properly not clear with short piece of code I pasted, but thething is: if the two if lines are TRUE and it execute return, you will not get any reward nor an achievement. 

So my conclusion is that one of the two IF is FALSE. So we need to answer that question. And thats why i wanted to see your config.yml or a part of it.

**Comment by Maxetto** [comment] 2016-05-23 14:08
Yeah, sure.

[config.txt](https://github.com/Rocologo/MobHunting/files/277613/config.txt)

**Comment by Rocologo** [comment] 2016-05-24 09:27
Now I have installed MobArena on my testserver and tested if I got reward. AND then I saw that MobArena gave me a Reward not MobHunting. See the screendump. Are you sure that it wasn't the same case with your reward? 
![2016-05-24_11 22 48](https://cloud.githubusercontent.com/assets/1008133/15498964/0d2134c4-21a2-11e6-9689-309ba8263e2b.png)

**Comment by Maxetto** [comment] 2016-05-24 11:58
Of course, I've got Creepercide, as I've said.

The message was clearly from MobHunting

**Comment by Rocologo** [comment] 2016-05-24 14:26
Okay. I forgot that. Hmmmm... I hlave no cluse at the moment on how it could happen :-(

**Comment by Rocologo** [comment] 2016-05-25 06:29
I have just tested Axe-Murder achievement and I didnt get a reward for that. I tested axe murder because it was easy for me to test, and then I suddenly realised that it might be something with the specific achievement. I have looked at the code pieces where the player kills a mob, but Creepercide is special because it is a creeper killing a creeper! 

I think I know how to solve this now :-)

**Comment by Rocologo** [comment] 2016-05-25 09:40
This is fixed in V3.0.8. Root cause found. It was only indirect kills which was affected. So I found the problem in CreeperCide and FangMaster.

**Comment by Maxetto** [comment] 2016-05-25 11:56
Nice, as I thought, it was a flaw in Achievements with EntityDamageEvent :wink:

**Comment by Rocologo** [comment] 2016-05-31 00:29
V3.0.8 released

**Closed by Rocologo** 2016-05-31 00:29 UTC
Labels: bug
