### ISSUE TITLE
On disable freeze!

### ISSUE THREAD

**Issue by FlashLight34** [Rocologo/MobHunting#47] opened 2016-05-29 01:20 UTC
[03:18:08] [Server thread/INFO]: Stopping the server
[03:18:08] [Server thread/INFO]: Stopping server
[03:18:08] [Server thread/INFO]: [MobHunting] Disabling MobHunting v3.0.7
[03:18:44] [User Authenticator #97/INFO]: UUID of player Precepts is 859903a7-b649-42bd-95b9-1660f0c9d5eb
[03:19:13] [Server console handler/ERROR]: Exception handling console input
java.io.IOException: Input/output error
	at java.io.FileInputStream.readBytes(Native Method) ~[?:1.8.0_45-internal]
	at java.io.FileInputStream.read(FileInputStream.java:255) ~[?:1.8.0_45-internal]
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246) ~[?:1.8.0_45-internal]
	at java.io.BufferedInputStream.read(BufferedInputStream.java:265) ~[?:1.8.0_45-internal]
	at org.bukkit.craftbukkit.libs.jline.internal.NonBlockingInputStream.read(NonBlockingInputStream.java:248) ~[spigot-1.9.4.jar:git-Spigot-8a048fe-a022dd2]
	at org.bukkit.craftbukkit.libs.jline.internal.InputStreamReader.read(InputStreamReader.java:261) ~[spigot-1.9.4.jar:git-Spigot-8a048fe-a022dd2]
	at org.bukkit.craftbukkit.libs.jline.internal.InputStreamReader.read(InputStreamReader.java:198) ~[spigot-1.9.4.jar:git-Spigot-8a048fe-a022dd2]
	at org.bukkit.craftbukkit.libs.jline.console.ConsoleReader.readCharacter(ConsoleReader.java:2145) ~[spigot-1.9.4.jar:git-Spigot-8a048fe-a022dd2]
	at org.bukkit.craftbukkit.libs.jline.console.ConsoleReader.readLineSimple(ConsoleReader.java:3183) ~[spigot-1.9.4.jar:git-Spigot-8a048fe-a022dd2]
	at org.bukkit.craftbukkit.libs.jline.console.ConsoleReader.readLine(ConsoleReader.java:2333) ~[spigot-1.9.4.jar:git-Spigot-8a048fe-a022dd2]
	at org.bukkit.craftbukkit.libs.jline.console.ConsoleReader.readLine(ConsoleReader.java:2269) ~[spigot-1.9.4.jar:git-Spigot-8a048fe-a022dd2]
	at org.bukkit.craftbukkit.libs.jline.console.ConsoleReader.readLine(ConsoleReader.java:2257) ~[spigot-1.9.4.jar:git-Spigot-8a048fe-a022dd2]
	at net.minecraft.server.v1_9_R2.DedicatedServer$2.run(DedicatedServer.java:83) [spigot-1.9.4.jar:git-Spigot-8a048fe-a022dd2]

**Comment by Rocologo** [comment] 2016-05-29 05:23
Are you using Mysql or Sqlite?

**Comment by Rocologo** [comment] 2016-05-29 05:24
Did you press Control C to continue?

**Comment by FlashLight34** [comment] 2016-05-29 14:14
sqlite and i rent a server :|

**Comment by Rocologo** [comment] 2016-05-30 06:55
I have made a new fix for this, trying to solve this problem. :-( I will release a version 3.0.8 today, if my own test does not show any errors.

**Comment by Rocologo** [comment] 2016-05-31 20:41
Let me know if you still see this freezing/crash problem, when you have installed v3.1.0 i have spend alot of time on this trying to find a ways to solve the problem. I dont think v3.1.0 freezes the server but im not sure if shutdown works 100%yet.

**Comment by FlashLight34** [comment] 2016-06-05 15:22
[17:20:50 INFO]: Debug logging is disabled
[17:20:50 INFO]: Server Ping Player Sample Count: 12
[17:20:50 INFO]: Using 4 threads for Netty based IO
[17:20:50 INFO]: [MobHunting] Disabling MobHunting v3.1.5

same here :(

**Comment by Rocologo** [comment] 2016-06-05 16:06
Yes, I have seen it too, since I asked. :-(

**Comment by Rocologo** [comment] 2016-06-09 09:03
Hi again

I have changed the way the plugin is shutdown in V3.1.8, and done some testing. At this time I have not seen any errors at all. 

Please let me know if you see the error again.

If I don't hear from you within a week I will close the incident.

Cross my fingers....

**Comment by Rocologo** [comment] 2016-06-09 19:18
I still have a problem 😈

**Comment by Rocologo** [comment] 2016-06-13 23:38
Okay - this time i think i found the root cause of this error ... Please me know if you see the error when you have installed 3.1.9

**Comment by Rocologo** [comment] 2016-06-15 11:46
This time i finally think I got it!!! This bug has been a problem for more than a year. The previous developer worked on it too!!!

Thank you for your patience!

**Comment by Rocologo** [comment] 2016-06-15 17:57
ohhhhh no :-(

**Comment by FlashLight34** [comment] 2016-06-27 23:55
Mobhunting 3.2.3 same in  :(

**Comment by Rocologo** [comment] 2016-06-28 21:46
I haven't seen the error for almost a week now :-( 

Please show me the output in the console before if freezes. I have written some debug info.

**Comment by Rocologo** [comment] 2016-06-30 20:47
Today I decided to check MobHunting on a Glowstone server to make sure that i was still supported. 

And then because Glostone server works different from Spigot i got another error when shutting down, and then i realizied what was wrong. 

This is now fixed in v3.2.5

I will though keep this ticket open another week.

Please let me know if you see the freezing error again after installing v3.2.5

**Comment by Rocologo** [comment] 2016-07-11 00:40
I think this can beclosed now

**Closed by Rocologo** 2016-07-11 00:40 UTC
Labels: bug
