### ISSUE TITLE
Class cast exception v5.0.4

### ISSUE THREAD

**Issue by ArtNRG** [Rocologo/MobHunting#285] opened 2017-08-12 21:16 UTC
https://pastebin.com/XSS2YSQU

**Comment by Rocologo** [comment] 2017-08-13 11:32
This is fixed in V5.0.5

When showing the error form the console, you should also paste the lines AFTER 
"Caused by: java.lang.ClassCastException" 

The last lines are actually the most important because the have references to lines in my source code :-)

**Closed by Rocologo** 2017-08-13 11:32 UTC
