### ISSUE TITLE
Error on Paper Spigot 1.12.2.

### ISSUE THREAD

**Issue by TheIntelloBox** [Rocologo/MobHunting#369] opened 2018-03-07 18:50 UTC
https://hastebin.com/yevasexoru.vbs

**Comment by Rocologo** [comment] 2018-03-07 18:55
Have tried to make a message_type in config.yml ? 

What did you write?

**Comment by TheIntelloBox** [comment] 2018-03-07 19:00
I wrote nothing. :x

**Comment by Rocologo** [comment] 2018-03-07 19:02
Okay, which mob did you kill? And i would like to see the config section of this mob?

**Comment by TheIntelloBox** [comment] 2018-03-07 19:15
This was in the console so I don't know. Here is my config : https://hastebin.com/aleviputit.coffeescript

**Comment by Rocologo** [comment] 2018-03-08 09:52
Hmm.. I have tried different settings but I cant provoke a NPE error, so at the moment I dont know whats trigger this bug in the console????

**Comment by TheIntelloBox** [comment] 2018-03-08 10:06
Have you tried with PWP ?

**Comment by Rocologo** [comment] 2018-03-08 10:10
Nope. Im only one on my test server... so its hard to test. But thinkink of this i will check the source code again

**Comment by Rocologo** [comment] 2018-03-10 08:42
I have three ticket with the same issue now :-) 

I hope the problem is solved in newest snapshot build 600 or newer

http://jenkins.lindegaard.one:8180/job/MobHunting/

**Comment by Rocologo** [comment] 2018-03-10 08:43
Please let me know if it works

**Comment by Rocologo** [comment] 2018-03-18 18:43
fixed in 5.5.7

**Closed by Rocologo** 2018-03-18 18:43 UTC

**Comment by TheIntelloBox** [comment] 2018-03-18 18:57
Thanks ! :D
