### ISSUE TITLE
EntityDeathEvent error

### ISSUE THREAD

**Issue by Sikatsu** [Rocologo/MobHunting#153] opened 2017-02-14 21:24 UTC
Spotted an error: http://pastebin.com/1qD1mdpe / http://pastebin.com/xQ2KxWW2

**Comment by woodenaxenet** [comment] 2017-02-16 20:52
Same here : It don't like snowballs.
[13:33:02] [Server thread/ERROR]: Could not pass event EntityDeathEvent to MobHunting v4.4.8
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.11.2-20170204a.jar:git-Spigot-d4f98a3-4448a7e]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.11.2-20170204a.jar:git-Spigot-d4f98a3-4448a7e]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.11.2-20170204a.jar:git-Spigot-d4f98a3-4448a7e]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.11.2-20170204a.jar:git-Spigot-d4f98a3-4448a7e]
	at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:392) [spigot-1.11.2-20170204a.jar:git-Spigot-d4f98a3-4448a7e]
	at net.minecraft.server.v1_11_R1.EntityLiving.die(EntityLiving.java:1079) [spigot-1.11.2-20170204a.jar:git-Spigot-d4f98a3-4448a7e]
	at net.minecraft.server.v1_11_R1.EntityLiving.damageEntity(EntityLiving.java:933) [spigot-1.11.2-20170204a.jar:git-Spigot-d4f98a3-4448a7e]
	at net.minecraft.server.v1_11_R1.EntityMonster.damageEntity(EntityMonster.java:44) [spigot-1.11.2-20170204a.jar:git-Spigot-d4f98a3-4448a7e]
	at net.minecraft.server.v1_11_R1.EntityWither.damageEntity(EntityWither.java:467) [spigot-1.11.2-20170204a.jar:git-Spigot-d4f98a3-4448a7e]
	at net.minecraft.server.v1_11_R1.EntitySnowball.a(SourceFile:45) [spigot-1.11.2-20170204a.jar:git-Spigot-d4f98a3-4448a7e]
	at net.minecraft.server.v1_11_R1.EntityProjectile.A_(EntityProjectile.java:167) [spigot-1.11.2-20170204a.jar:git-Spigot-d4f98a3-4448a7e]
	at net.minecraft.server.v1_11_R1.World.entityJoinedWorld(World.java:1629) [spigot-1.11.2-20170204a.jar:git-Spigot-d4f98a3-4448a7e]
	at net.minecraft.server.v1_11_R1.World.h(World.java:1604) [spigot-1.11.2-20170204a.jar:git-Spigot-d4f98a3-4448a7e]
	at net.minecraft.server.v1_11_R1.World.tickEntities(World.java:1430) [spigot-1.11.2-20170204a.jar:git-Spigot-d4f98a3-4448a7e]
	at net.minecraft.server.v1_11_R1.WorldServer.tickEntities(WorldServer.java:618) [spigot-1.11.2-20170204a.jar:git-Spigot-d4f98a3-4448a7e]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:814) [spigot-1.11.2-20170204a.jar:git-Spigot-d4f98a3-4448a7e]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.11.2-20170204a.jar:git-Spigot-d4f98a3-4448a7e]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot-1.11.2-20170204a.jar:git-Spigot-d4f98a3-4448a7e]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot-1.11.2-20170204a.jar:git-Spigot-d4f98a3-4448a7e]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
Caused by: org.bukkit.command.CommandException: Unhandled exception executing command 'mobhunt' in plugin MobHunting v4.4.8
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.11.2-20170204a.jar:git-Spigot-d4f98a3-4448a7e]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.11.2-20170204a.jar:git-Spigot-d4f98a3-4448a7e]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:650) ~[spigot-1.11.2-20170204a.jar:git-Spigot-d4f98a3-4448a7e]
	at one.lindegaard.MobHunting.MobHuntingManager.onMobDeath(MobHuntingManager.java:1382) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor106.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_111]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_111]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.11.2-20170204a.jar:git-Spigot-d4f98a3-4448a7e]
	... 19 more
Caused by: java.lang.NumberFormatException: For input string: "MH_b8c4d2aa"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[?:1.8.0_111]
	at java.lang.Long.parseLong(Long.java:589) ~[?:1.8.0_111]
	at java.lang.Long.valueOf(Long.java:776) ~[?:1.8.0_111]
	at java.lang.Long.decode(Long.java:928) ~[?:1.8.0_111]
	at java.util.UUID.fromString(UUID.java:198) ~[?:1.8.0_111]
	at one.lindegaard.MobHunting.rewards.CustomItems.getCustomtexture(CustomItems.java:57) ~[?:?]
	at one.lindegaard.MobHunting.mobs.MinecraftMob.getHead(MinecraftMob.java:623) ~[?:?]
	at one.lindegaard.MobHunting.commands.HeadCommand.onCommand(HeadCommand.java:143) ~[?:?]
	at one.lindegaard.MobHunting.commands.CommandDispatcher.onCommand(CommandDispatcher.java:116) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.11.2-20170204a.jar:git-Spigot-d4f98a3-4448a7e]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.11.2-20170204a.jar:git-Spigot-d4f98a3-4448a7e]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:650) ~[spigot-1.11.2-20170204a.jar:git-Spigot-d4f98a3-4448a7e]
	at one.lindegaard.MobHunting.MobHuntingManager.onMobDeath(MobHuntingManager.java:1382) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor106.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_111]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_111]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.11.2-20170204a.jar:git-Spigot-d4f98a3-4448a7e]
	... 19 more

**Comment by Sikatsu** [comment] 2017-02-17 15:12
The error itself is quite different though

**Comment by Sikatsu** [comment] 2017-02-18 19:21
@Rocologo This error is really spammy, perhaps any information?

**Comment by Rocologo** [comment] 2017-02-19 12:11
This line 

Caused by: java.lang.NumberFormatException: For input string: "MH_b8c4d2aa"
at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[?:1.8.0_111]

tells me that it is something with the cmd line to be run when a mob is killed. I need to the the cmd line for the given mob. Please enable /mh debug so I get the debug information.

**Comment by Rocologo** [comment] 2017-02-19 19:37
The MyPet error should be fixed now in V4.5.0

**Comment by Sikatsu** [comment] 2017-02-19 19:38
Awesome, I didn't have time yet to do the mh debug. Pretty busy weekend. Will test 4.5.0 soon!

**Comment by Rocologo** [comment] 2017-02-19 19:40
There are two error on this ticket. Your bug with MyPet killing mobs has been fixed now. 

I have not tested the snowball error yet.

**Comment by Sikatsu** [comment] 2017-02-19 19:44
Oh, I don't know about the snowball issue though. Just the MyPet error was a bitch. ^^

**Comment by woodenaxenet** [comment] 2017-02-19 22:44
Look better then the last thanks for the update.

[15:37:47] [Server thread/INFO]: [@: Object successfully summoned]
[15:37:58] [Server thread/INFO]: [MobHunting][Debug] WARNING: The firewall was shut from CraftWither, this situation is not handled by MobHunting.
[15:37:59] [Server thread/INFO]: [MobHunting][Debug] WARNING: The firewall was shut from CraftWither, this situation is not handled by MobHunting.
[15:38:04] [Server thread/INFO]: [MobHunting][Debug] IamU picked up $18.78 money. (# of rewards left=5)
[15:38:10] [Server thread/INFO]: [MobHunting][Debug] WARNING: The firewall was shut from CraftWither, this situation is not handled by MobHunting.
[15:38:12] [Server thread/INFO]: [MobHunting][Debug] WARNING: The firewall was shut from CraftWither, this situation is not handled by MobHunting.
[15:38:14] [Server thread/INFO]: [MobHunting][Debug] lastKillstreakLevel=2
[15:38:14] [Server thread/INFO]: [MobHunting][Debug] newKillstreakLevel=2
[15:38:14] [Server thread/INFO]: [MobHunting][Debug] Checking if player is grinding mob in the same region within a range of 15.0 blocks
[15:38:14] [Server thread/INFO]: [MobHunting][Debug] DampendKills=0
[15:38:14] [Server thread/INFO]: [MobHunting][Debug] Basic Prize=$1,484.97 for killing a Wither
[15:38:14] [Server thread/INFO]: [MobHunting][Debug] Multiplier: Difficulty = 2.0
[15:38:14] [Server thread/INFO]: [MobHunting][Debug] Killstreak=14, level=2, multiplier=2.0 
[15:38:14] [Server thread/INFO]: [MobHunting][Debug] RecordAchievement: hunting-level1-wither has 9 kills
[15:38:14] [Server thread/INFO]: [MobHunting][Debug] $5,939.88 was dropped on the ground as item SKULL (# of rewards=5)
[15:38:14] [Server thread/INFO]: [MobHunting][Debug] RecordKill: IamU killed a Wither (Minecraft)
[15:38:14] [Server thread/INFO]: [MobHunting][Debug] random double=0.07717503238363876 < chance=1.0
[15:38:14] [Server thread/INFO]: [MobHunting][Debug] command to be run is:mobhunt head give IamU Wither|give IamU diamond 10
[15:38:14] [Server thread/INFO]: [MobHunting][ERROR] Could not run cmd:"mobhunt head give IamU Wither when Mob:Wither was killed by IamU
[15:38:14] [Server thread/INFO]: CONSOLE issued server command: /give IamU diamond 10
[15:38:14] [Server thread/INFO]: Giving 10 of diamond to IamU.
[15:38:14] [Server thread/INFO]: [MobHunting][Debug] Description to be send:You got a Wither skull and 10 Diamonds.
[15:38:14] [Server thread/INFO]: [MobHunting][Debug] The reward was hit by SNOWBALL and removed. (# of rewards left=4)
[15:38:20] [Server thread/INFO]: [MobHunting][Debug] Refeshed 17 leaderboards.
[15:38:21] [Server thread/INFO]: CONSOLE issued server command: /list 
[15:38:21] [Server thread/INFO]: There are 1 out of maximum 41 players online.
[15:38:21] [Server thread/INFO]: player: IamU
[15:38:21] [Server thread/INFO]: [MobHunting][Debug] lastKillstreakLevel=2
[15:38:21] [Server thread/INFO]: [MobHunting][Debug] newKillstreakLevel=2
[15:38:21] [Server thread/INFO]: [MobHunting][Debug] Checking if player is grinding mob in the same region within a range of 15.0 blocks
[15:38:21] [Server thread/INFO]: [MobHunting][Debug] DampendKills=0
[15:38:21] [Server thread/INFO]: [MobHunting][Debug] Basic Prize=$10.89 for killing a Zombie
[15:38:21] [Server thread/INFO]: [MobHunting][Debug] Multiplier: Difficulty = 2.0
[15:38:21] [Server thread/INFO]: [MobHunting][Debug] Killstreak=15, level=2, multiplier=2.0 
[15:38:21] [Server thread/INFO]: [MobHunting][Debug] RecordAchievement: hunting-level1-zombie has 95 kills
[15:38:21] [Server thread/INFO]: [MobHunting][Debug] $43.56 was dropped on the ground as item SKULL (# of rewards=5)
[15:38:21] [Server thread/INFO]: [MobHunting][Debug] RecordKill: IamU killed a Zombie (Minecraft)
[15:38:21] [Server thread/INFO]: [MobHunting][Debug] random double=0.6894399726314686 < chance=0.05

**Comment by Rocologo** [comment] 2017-02-20 08:28
Fixed in V4.5.2

**Closed by Rocologo** 2017-02-20 08:28 UTC
