### ISSUE TITLE
WARN java.lang.IllegalStateException

### ISSUE THREAD

**Issue by krustymk** [Rocologo/MobHunting#143] opened 2017-02-10 15:08 UTC
http://pastebin.com/4Z0nKFGg

**Comment by Rocologo** [comment] 2017-02-10 15:15
This means that your world-board.yml file contains wrong data.

I need to see the file.

**Comment by krustymk** [comment] 2017-02-12 09:01
well,, apart from this its empty

# This file is automatically generated. Do NOT edit this file manually or you risk losing all leaderboards if you mistype something.
'0':
  world: 6b15681e-eb44-4b25-985c-984489532d6e
  position:
    ==: Vector
    x: -28.0
    y: 21.0
    z: -20.0
  facing: EAST
  horizontal: true
  periods:
  - AllTime
  stats:
  - total_kill
  width: 3
  height: 3

**Comment by krustymk** [comment] 2017-02-12 09:02
another (a couple of worlds)

# This file is automatically generated. Do NOT edit this file manually or you risk losing all leaderboards if you mistype something.
'0':
  world: 33854434-ef50-4d50-8827-4cbd2a535b19
  position:
    ==: Vector
    x: -8.0
    y: 66.0
    z: -10.0
  facing: EAST
  horizontal: true
  periods:
  - Week
  stats:
  - total_kill
  width: 3
  height: 3
'1':
  world: 33854434-ef50-4d50-8827-4cbd2a535b19
  position:
    ==: Vector
    x: 12.0
    y: 66.0
    z: -10.0
  facing: EAST
  horizontal: true
  periods:
  - AllTime
  stats:
  - Skeleton_kill
  width: 3
  height: 3
'2':
  world: 33854434-ef50-4d50-8827-4cbd2a535b19
  position:
    ==: Vector
    x: 10.0
    y: 66.0
    z: -8.0
  facing: SOUTH
  horizontal: true
  periods:
  - Week
  stats:
  - total_kill
  width: 3
  height: 3
'3':
  world: 33854434-ef50-4d50-8827-4cbd2a535b19
  position:
    ==: Vector
    x: 10.0
    y: 66.0
    z: -8.0
  facing: SOUTH
  horizontal: true
  periods:
  - AllTime
  stats:
  - Creeper_kill
  width: 3
  height: 3
'4':
  world: 33854434-ef50-4d50-8827-4cbd2a535b19
  position:
    ==: Vector
    x: -10.0
    y: 66.0
    z: -12.0
  facing: NORTH
  horizontal: true
  periods:
  - Week
  stats:
  - Zombie_kill
  width: 3
  height: 3
'5':
  world: 33854434-ef50-4d50-8827-4cbd2a535b19
  position:
    ==: Vector
    x: 8.0
    y: 66.0
    z: -10.0
  facing: WEST
  horizontal: true
  periods:
  - AllTime
  stats:
  - total_kill
  width: 3
  height: 3
'6':
  world: 33854434-ef50-4d50-8827-4cbd2a535b19
  position:
    ==: Vector
    x: 10.0
    y: 66.0
    z: -12.0
  facing: NORTH
  horizontal: true
  periods:
  - AllTime
  stats:
  - Zombie_kill
  width: 3
  height: 3
'7':
  world: 33854434-ef50-4d50-8827-4cbd2a535b19
  position:
    ==: Vector
    x: -10.0
    y: 66.0
    z: -8.0
  facing: SOUTH
  horizontal: true
  periods:
  - Week
  stats:
  - Creeper_kill
  width: 3
  height: 3
'8':
  world: 33854434-ef50-4d50-8827-4cbd2a535b19
  position:
    ==: Vector
    x: -12.0
    y: 66.0
    z: -10.0
  facing: WEST
  horizontal: true
  periods:
  - Week
  stats:
  - Skeleton_kill
  width: 3
  height: 3

**Comment by Rocologo** [comment] 2017-02-12 10:15
One of your files contains something wrong. I cant see any errors in these two. 

Either its none of these or its something I dont see.

Have you tried to edit the files manually? 

I will see if I can improve the error text so we get an idea of whats wrong.

**Comment by Rocologo** [comment] 2017-02-12 10:21
I checked the code, and you can get this error if you have a file for a deleted world. 

Also I would like to see the real server log, because Multicraft has 
Skipped 22 lines due to rate limit (30/s)

**Comment by Rocologo** [comment] 2017-02-12 10:45
If you try build 283 or newer
http://jenkins.lindegaard.one:8180/job/MobHunting/ 

You will get the UUID of the missing world, if this is the root cause for this error.

**Comment by krustymk** [comment] 2017-02-13 15:22
Used the latest build
http://pastebin.com/Mbf6Uy44

**Comment by Rocologo** [comment] 2017-02-13 18:56
It looks like you have a Leaderboard with no or an Invalid StatType. 

I have added a test and a warning, if this happens in next release.

**Comment by krustymk** [comment] 2017-02-13 19:35
ah.. ok, i let someone doing some building work around where the leaderboard is recently... i wonder if they altered something? Thanks :)

**Comment by Rocologo** [comment] 2017-02-13 19:52
Well, I want my plugin to handle and write nice warnings in the log if this happens, I dont want "ugly" warnings like you got. So if we can find the error I will make a fix/nice warning.

I have just released V4.4.7 which should tell you were the leaderboard is.

**Comment by krustymk** [comment] 2017-02-13 20:01
You sir are awesome! Top man :) 
Thanks for your help

**Comment by Rocologo** [comment] 2017-02-13 21:45
Lets see if we can find the problem, its sometimes not that easy!

**Comment by krustymk** [comment] 2017-02-13 21:56
Just installed 4.4.7 and... sorry :/
http://pastebin.com/7bNNJ3Rt

**Comment by krustymk** [comment] 2017-02-13 21:56
Im going to delete all the boards and start again,

**Comment by Rocologo** [comment] 2017-02-13 22:09
This error can ONLY happen if you have a leaderboard in one of the leaderboard configuration files where the location is null (does not exist)

You dont need to delete them all because of me, I would like to find the error to understand why this happens. I you have this error other will have it too at some point.

**Comment by krustymk** [comment] 2017-02-13 22:13
ok, well... i deleted the 2 leaderboard world files and did a reload on the plugin.... turned out not to be a good idea (crashed java on the box) http://pastebin.com/v6GXRc5v
But, on the plus side, the error has gone :)
Nealry shit my pants though haha

**Comment by Rocologo** [comment] 2017-02-13 22:18
You are not the only one having problems with reloading the plugin. /mh reload works on both my servers and I cant replicate this error :-(

**Comment by krustymk** [comment] 2017-02-13 22:37
I think it weas trying to write to the files i had deleted? Pretty silly do delete them whilst the server was running really

**Comment by Rocologo** [comment] 2017-02-13 22:48
Agree changing config files can be dangerous when its not mean to...

**Comment by Rocologo** [comment] 2017-02-13 22:49
Maybe if you had disabled the plugin with plugman and then deleted the file...

**Comment by Rocologo** [comment] 2017-02-14 07:39
Maybe if you had disabled the plugin with plugman and then deleted the file...


Can I close this ticket now?

**Comment by krustymk** [comment] 2017-02-16 11:55
Sorry.. yes i believe it can be closed
Thanks for your help :)

**Closed** 2017-02-16 13:34 UTC
Labels: bug, question
