### ISSUE TITLE
MH 4.5.2 crashes game as soon as a mob is killed

### ISSUE THREAD

**Issue by datsme** [Rocologo/MobHunting#166] opened 2017-02-20 17:23 UTC
I just updated my Spigot and MH today to 4.5.2 (see attached). The game starts fine no errors or warnings.
As soon as I kill a mob though the entire game freezes and locks the server up.  
If I disable MH everything else works fine. Here is a copy of the crash report.
 
[crash-2017-02-20_08.57.17-server.txt](https://github.com/Rocologo/MobHunting/files/788122/crash-2017-02-20_08.57.17-server.txt)

**Comment by Rocologo** [comment] 2017-02-20 20:28
I have no idea whats could cause this. I have most of your plugins too, running on my server. 

I would like to see the full server.log until you have killed one mob and the server crashes. I want to see that everything looks fine.  And please enable debug first with /mh debug. 

Use pastebin.com

**Comment by datsme** [comment] 2017-02-21 14:49
I updated my Spigot again this morning thinking perhaps it was a Spigot issue as well as re-downloaded MH 4.5.2 to make sure it wasn't a corrupted file. 
As requested I started the game, turned on /mh debug and shot a creeper with my bow and the problem persists.

Here is a link to the log that you requested via pastebin:
http://pastebin.com/CUf5WvmY

**Comment by Rocologo** [comment] 2017-02-21 20:05
You have changed the leaderboard update to 6 seconds. I think this could be a reason for your problems. You ask the server to query the database every 6th second, which could easily cause database lockings.

**Comment by Rocologo** [comment] 2017-02-21 20:07
I also notice that MH throws a warnjng when you should with an arrow, this is a bug. I will check and fix that. But dont think this causes a server crash.

**Comment by Rocologo** [comment] 2017-02-21 21:03
PS. The warning about the ARROW is removed in next release V4.5.3

**Comment by Rocologo** [comment] 2017-02-21 21:05
And I have added a minimun value on the leaderboard update. Minimum is set to 1200 ticks = 2 minutes but i recommend to set this to 6000 or 12000 ticks = 5 - 10 minutes.

**Comment by datsme** [comment] 2017-02-21 22:20
Thanks I will make the changes and let you know probably tomorrow. This allows me time so  I can take the server down when no players are on.

**Comment by Rocologo** [comment] 2017-02-21 22:36
You can try news build here if you want to.

http://jenkins.lindegaard.one:8180/job/MobHunting/

**Comment by datsme** [comment] 2017-02-22 13:44
4.5.3 gets a funny error lol 
 [MobHunting][Debug] Mobhunting could not find the prize for killing this mob: Armor Stand (ARMOR_STAND)
Let me go catch one of these elusive mobs hehe

**Comment by datsme** [comment] 2017-02-22 15:10
Its definitely something in my config file. (Stupid User Error hehehe) 
I deleted the entire folder and ran a fresh version and let it repopulate the files and then it worked.
I then copied my original config file back and it does the error again. 
Finally I restored the new config and it works again so verified its in my config. 

I hate to be a pain because this sort of issue I can usually fix but I do not see anything I changed that might cause this weird issue. I also verified it is still a valid YML file on-line just in case my notepad++ was saving the format wrong.
So I am really baffled as to what is going on. Would you mind taking a look at my settings?
Here is the pastebin:
http://pastebin.com/misf4Fhj

**Comment by datsme** [comment] 2017-02-22 18:59
More discoveries....found it has to do with Gringotts support and drop-money-on-ground.
drop-money-on-ground: true
drop-money-on-ground-itemtype: ITEM
drop-money-on-ground-item: EMERALD
disable-integration-gringotts: false
CRASH as soon as you change "itemtype" to ITEM
change "disable-integration-gringotts": true
Now emeralds automatically go into your gringotts vault not your inventory (I think this is more desirable anyway as it doesn't take up inventory space. So not really sure what your gringotts integration is supposed to do but for me it crashes my server. Which did not happen like two or three   MobHunting versions ago. Hope this helps ya chase down the issue.

P.S.  in the config file it states;
  # Dark room mobspawners usually collect items in a HOPPER. This is denied by default.
  # If you want HOPPERS to collect MobHunting Money rewards 
  # set "deny-hoppers-to-pickup-money-on-ground"=true

Shouldn't it be "false" -  # If you want HOPPERS to collect MobHunting Money rewards

**Comment by Rocologo** [comment] 2017-02-22 20:14
Thank you for helping me with the investigation. I will test the Gringotts integration on my test server to see if I can provoke a crash and the I will fix it.

It should not need to disable the integration to Gringotts if you use Gringotts. I dont use Gringotts my self so i dont test the integration very often

**Comment by Rocologo** [comment] 2017-02-23 17:21
PS. You dont need to disabled all the plugins you dont use. You only need to disable integration if you are having problems with the integration. Or if you want the text messages to appear in the chat.

**Comment by Rocologo** [comment] 2017-02-23 17:23
I can reproduce the crash using your settings, so now I can fix it :-)

**Comment by Rocologo** [comment] 2017-02-23 17:38
I can reproduce the crash using your settings, so now I can fix it :-)

**Comment by Rocologo** [comment] 2017-02-23 17:44
I have found the Gringotts problem. I made a stupid bug when I introduced the "Bag of gold" I created a never ending loop dropping emeralds until the server crashed because of "out of memory" This is fixed in V4.5.3 which I will release tonight.

The HOPPER text is corrected as well :-)

**Comment by Rocologo** [comment] 2017-02-23 22:26
V4.5.3 is released, but I do still have a problem with the Bag of gold texture.

**Comment by Rocologo** [comment] 2017-02-23 22:59
Let me know if this solves your problems so I can close the ticket?

**Comment by Rocologo** [comment] 2017-02-23 23:00
PS an please make a nice review of the plugin :-)

**Comment by Rocologo** [comment] 2017-02-24 16:50
And

**Closed by Rocologo** 2017-02-24 16:50 UTC
Labels: bug
