### ISSUE TITLE
Happy Hour timeleft placeholder broken

### ISSUE THREAD

**Issue by Sikatsu** [Rocologo/MobHunting#512] opened 2019-05-19 15:22 UTC
Hey,

I did /mh happyhour twice in the same minute:

http://prntscr.com/nqk6sm

40 minutes is correct, not sure why it first said 45. Small issue?

**Comment by Rocologo** [comment] 2019-05-26 08:14
I cant reproduce this bug...

**Comment by Sikatsu** [comment] 2019-05-26 09:36
It's definatly there though, happens almost everytime when I use it.

**Comment by Sikatsu** [comment] 2019-06-10 12:28
@Rocologo 

This is definatly still a bug, people use /mh happyhour and sometimes it says (for example) -20 minutes AFTER the happyhour was ended already. But it's also inaccurate while an happyhour is running.

**Comment by Sikatsu** [comment] 2019-06-17 14:26
@Rocologo 

Last weekend I got some reports from players that Happy Hour was still running. When I checked it with the /mh happyhour command this was the output:

> mh happyhour=> [20:31:46 INFO]: Happy Hour duurt nog -17 minuten.

It should have ended 17 minutes ago, but instead it said that it still lasts 17 minutes.
When players kill mobs it also still says the happyhour applies. (The {bonuses} placeholder)

I think there is more wrong then it just being cosmetic, I think it doesn't end happy hour like it should.

**Comment by Sikatsu** [comment] 2019-06-19 17:56
@Rocologo So this is fixed?

**Comment by Rocologo** [comment] 2019-06-19 18:29
I Hope so. I have not had a Lot of time to test, but I think it is better 
now.

**Comment by Sikatsu** [comment] 2019-06-22 21:46
@Rocologo I got a report, which i'll quote: ''Happy hour is still not working properly. /mh happyhour says 0 minutes but its been going on for 5 minutes over time now :p''

**Comment by Rocologo** [comment] 2019-06-23 14:06
It seems like a simple task, but .... :-(

I really hope the problem is fixed in V6.6.8

**Comment by Sikatsu** [comment] 2019-06-29 17:52
When I login, it said 15 minutes. When I use /mh happyhour right after it, it says 9 minutes.

The 9 minutes are correct.

http://prntscr.com/o8dg5x

**Comment by Rocologo** [comment] 2019-07-05 15:13
Sorry I did not test login. I will have a look at that :-)

**Comment by Rocologo** [comment] 2019-07-05 15:29
I think it is fixed now: https://fractal.lindegaard.one:8181/job/MobHunting/835/

**Closed** 2019-07-06 18:19 UTC
