### ISSUE TITLE
Bags of gold don't stack / can't sell them

### ISSUE THREAD

**Issue by Spejhle** [Rocologo/MobHunting#312] opened 2017-10-17 23:26 UTC
Hi,
recently i found MH plugin and decided to test it, but something is wrong. Bags of gold dropped by mobs don't stack. Instead they just create a new bag on pick up and fill the inventory with it. While trying to combine them in the inventory the console goes crazy and when i try command /mh money sell, game sends me a message: An internal error occured while attempting to perform this command. Again lot of errors apears in console. I tried to minimize plugin count so i only have Craftconomy, EssentialsX, MobHunting, PermissionsEx and Vault. Here is my log:
[latest.log](https://github.com/Rocologo/MobHunting/files/1392957/latest.log)

I would be glad for any advice, anyway thank you for your time

**Comment by Rocologo** [comment] 2017-10-18 14:22
Ít looks like you have use a "," instead of a "." in your config.yml file.

Caused by: java.lang.NumberFormatException: For input string: "8,56"

**Comment by Rocologo** [comment] 2017-10-18 14:32
I would like to see your rewards.yml file?

**Comment by Rocologo** [comment] 2017-10-18 14:56
This bug should be fixed in build 483... When you have confirmed that it works on NEW Bags of gold then I will make a release

Please test and let me know the answer fast.... (if possible)
https://fractal.lindegaard.one:8181/job/MobHunting/

**Comment by Spejhle** [comment] 2017-10-18 16:04
Sorry i was at work. Unfortunatelly nothing changed. Anyway i didn't change anything in any config. Just downloaded and played as it was

**Comment by Rocologo** [comment] 2017-10-18 16:06
Did you get a new bag of gold to sell? 

Also I would like to see the error from your console? This one is hard to test for me, because my Java version is different from yours.

**Comment by Spejhle** [comment] 2017-10-18 16:10
yes, i dropped new bag of gold... few of them, again they don't stack. While trying to sell them, this time game didn't show any message, but nothing happened and console is full of errors. I'll attach them in a moment

**Comment by Spejhle** [comment] 2017-10-18 16:20
here is the log file
[latest.log](https://github.com/Rocologo/MobHunting/files/1395437/latest.log)

should i update java to a specific version?

**Comment by Spejhle** [comment] 2017-10-18 16:35
Also... is this a normal view of description?

![bag of gold](https://user-images.githubusercontent.com/32885879/31730692-fdc76ce4-b432-11e7-87d4-c04facc4600a.png)

**Comment by Rocologo** [comment] 2017-10-18 17:35
If you install ProtocolLib the lores will be removed. But I still see the error: It says "7,5000" and it should say "7.5000"

I have to search my code for this bug. Unfortunately I have no more time today. My wife think I need to do something else :-) 

BUT made a fast fix, trying once more so please test build 485
https://fractal.lindegaard.one:8181/job/MobHunting/

Again make a new Bag before trying

**Comment by Spejhle** [comment] 2017-10-18 17:42
i'm on it. I'll let you know. But thanks for the effords! GL&HF

**Comment by Spejhle** [comment] 2017-10-18 18:51
So... how to describe this situation... updated MH on test server... no bag drops at all. /mh money sell still not working returning lot of errors. So i decided to do one more test... i replaced MH on my main server with all the gazilions of plugins. And it miraculously worked. Dozens of bags merging into one and /mh money sell works if i have the bag selected in my hand. Console is silent too, so i guess it worked. Really thanks for help

**Comment by Rocologo** [comment] 2017-10-18 21:21
My guess is that you forgot to delete the old har on your test server?  If not please show me the error from the console

**Comment by Spejhle** [comment] 2017-10-18 21:41
i believe it is this one

[2017-10-18-8.log](https://github.com/Rocologo/MobHunting/files/1396442/2017-10-18-8.log)

**Comment by Rocologo** [comment] 2017-10-19 10:02
Released in V5.1.5

**Closed by Rocologo** 2017-10-19 10:02 UTC
