### ISSUE TITLE
Achievements screen

### ISSUE THREAD

**Issue by Raivs** [Rocologo/MobHunting#57] opened 2016-06-14 18:30 UTC
Can I ask to order in the achievements screen? As there are many achievements, the screen looks very chaotic. 

1) Do not show disabled ones, for example peacefull mob kill achievements if they are disabled
2) Show only those that are completed or in progress, excluding lover level ones. for example, if you have Skeleton 500 kills done, do not show the 250 one.
3) Have a different screens for completed achievements and those that are in progress and those that are not yet started (not really needed) 
4) Maybe have an option to have the achievement list printed in chat as it was before? (maybe _/mh kills list_)

**Comment by Rocologo** [comment] 2016-06-14 21:03
Thank you for making a detailed description.

1) Agreed.
2) I actually thought I had fixed that.
3) Agreed. And the three new mobs forces my to do this. I just forgot this inv3.1.9
4) try /mh achievements nogui       and i think i made a setting in config.yml to disable yhe gui ☺

**Comment by Raivs** [comment] 2016-06-15 00:20
sweet, /mh achievements nogui works!

**Comment by Raivs** [comment] 2016-06-15 00:25
>  2) I actually thought I had fixed that.

Might be true. I guess the 2500 kill achievement was not enabled and that's why it shows 1000 & 2500 of the same kind.

**Comment by Rocologo** [comment] 2016-06-15 04:19
Or maybe there is a minor bug. It should not show both at the same time.

**Comment by Rocologo** [comment] 2016-06-15 11:44
Fixed in V3.2.0 

You might still have a problem with the 1000 / 2500 kill achievement if it is saved in the database. You might need to delete this manually. I think I found the root cause and fixed the bug.

Thank you for reporting this!

Let me know if you find more bugs / more enhancements. (and create a new ticket then)

**Closed by Rocologo** 2016-06-15 11:44 UTC
Labels: bug, enhancement
