### ISSUE TITLE
Mixed use of cmd-run-frequency & cmd-run-frequency-base vs cmd-run-chance in config

### ISSUE THREAD

**Issue by South-Paw** [Rocologo/MobHunting#106] opened 2016-12-22 09:45 UTC
Hi there!

In plugin version 4.2.5, the following mobs, villagers and passives don't have `cmd-run-frequency` and `cmd-run-frequency-base` lines in the `config.yml` but they instead have `cmd-run-chance`.

- `evoker`
- `vex`
- `vindicator`
- `cartographer`
- `nitwit`
- `farmer`
- `priest`
- `blacksmith`
- `butcher`
- `librarian`
- `zombie-villager`
- `donkey`
- `llama`
- `mule`
- `skeletonhorse`
- `zombiehorse`

The `squid` also has a `squid-cmd-run-frequency` but not a `squid-cmd-run-frequency-base`.

1. It'd be nice to either have one or the other used consistently (either `frequency` or `chance`) instead of both or a mixture.
2. It'd also be good that if `chance` is remaining part of the plugin; then it is appropriately documented in the config.

Personally I'd prefer that `frequency` is used as it is easier to let the plugin decide the chance from the two variables than me manage working lots of them out.

Thanks for your continued work on this plugin! 🍰

**Comment by Rocologo** [comment] 2016-12-22 23:34
I the past I have noticed that frequency and frequency-base has been hard to understand for some server owners, so I decided to use chance instead. And since chance is calculated as freq/freq-base it doesn't really matter. 

I agree that the same terminology should be used, but has been low priority from my side, because its not a bug.

**Comment by South-Paw** [comment] 2016-12-23 08:55
That's understandable, but please do put it in the backlog as this is something that will only continue with more and more mobs added.

With regards to the `squid`, which has `squid-cmd-run-frequency` but not a `squid-cmd-run-frequency-base` - this is a bug and should be fixed.

**Comment by Rocologo** [comment] 2016-12-23 11:08
The missing "squid-cmd-run-frequency-base" is fixed in newest build if you need it now.
http://jenkins.lindegaard.one:8180/job/MobHunting/

I agree I have to be consistent - and it is on my "to do" list, the reason why it takes some time is that I need to find a way to calculate the chance from the old settings and then delete the old settings and create the new one, without manual input from the server owners. 

All new mobs has been added with "chance" instead of frequency.

**Comment by South-Paw** [comment] 2016-12-26 09:50
Awesome, thanks for your continued awesome work! 👍

**Comment by Rocologo** [comment] 2017-03-01 18:52
Fixed in next release

**Closed by Rocologo** 2017-03-01 18:52 UTC
Labels: enhancement
