### ISSUE TITLE
Error on mob death

### ISSUE THREAD

**Issue by Mavhill** [Rocologo/MobHunting#101] opened 2016-10-05 22:48 UTC
[mob hunt error.txt](https://github.com/Rocologo/MobHunting/files/512473/mob.hunt.error.txt)

Happens with the latest version 3.4.7 and the latest spigot release. With Citizens 2.0 also installed. Definitely a result of a mob being killed by a citizen npc.

**Comment by Rocologo** [comment] 2016-10-07 10:43
Thank you for a good description (npc killing a mob) this made it easy to find the bug and fix it. Please test build 127 or newer on my Jenkins Server:

http://jenkins.lindegaard.one:8180/

**Comment by Mavhill** [comment] 2016-10-07 23:44
Still getting an error.
[mob hunt error.txt](https://github.com/Rocologo/MobHunting/files/517286/mob.hunt.error.txt)
Definitely occurs on citizen killing mob
using this spigot spigot-1.10.2-R0.1-SNAPSHOT is the version it should test good with?

**Comment by Rocologo** [comment] 2016-10-08 06:50
Yes, i always test on 1.10.2 unless I know the problem is on an older version. I have nearly 20 test servers in different configurations ☺

Its very strange that the bug is still there,  I was sure I had fixed it. I will try once more and see if I can make one of my npc kill a mob.

**Comment by Rocologo** [comment] 2016-10-08 07:48
I cant reproduce the bug. Are you sure you removed the old version of MobHunting? :-)

I have updated my test server with Citizens Build 1420 and Sentinel Build66. I assume you use Sentinel? Then added target cavespider and spawned a cavespider in front of the NPC. The NPC immediately attacked and killed the cavespider, and now errors in the console on my server.

This is a part of my code and its hard to make some wrong here:
`		if (CitizensCompat.isNPC(damager) && !CitizensCompat.isSentryOrSentinel(damager))
			return;`

So either its not an NPC or its not an Sentinel? Maybe this assumption was wrong?

**Comment by Mavhill** [comment] 2016-10-08 19:27
Ok you sir are correct, i reloaded my config and now i get no errors. somewhat odd result for reloading a config but perhaps i had created an error myself. anyway problem fixed thanks for your hard work and patience.

**Comment by Rocologo** [comment] 2016-10-09 10:38
Perfect, then i close this ticket ☺

**Closed by Rocologo** 2016-10-09 10:38 UTC
