### ISSUE TITLE
Could not pass event EntityDeathEvent to MobHunting v6.5.5

### ISSUE THREAD

**Issue by kopper45** [Rocologo/MobHunting#496] opened 2019-05-10 19:58 UTC
[15:42:26] [Server thread/ERROR]: Could not pass event EntityDeathEvent to MobHunting v6.5.5
org.bukkit.event.EventException: null

This happens whenever I kill a Zombie or a Creeper, other mobs work fine and drop money etc. But for some reason Zombies and Creepers don't seem to work and I noticed this error in the server console.

**Comment by Rocologo** [comment] 2019-05-11 09:10
I to see the complete error text. The rest of the lines tell the developer where the problem is. The headline is not enough.

**Comment by kopper45** [comment] 2019-05-11 14:30
[15:42:08] [Server thread/INFO]: kopper45 issued server command: /night
[15:42:21] [Server thread/INFO]: kopper45 issued server command: /survival
[15:42:26] [Server thread/ERROR]: Could not pass event EntityDeathEvent to MobHunting v6.5.5
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:320) ~[spigot-1.14.jar:git-Spigot-1eece4f-6ceffb0]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.14.jar:git-Spigot-1eece4f-6ceffb0]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:520) ~[spigot-1.14.jar:git-Spigot-1eece4f-6ceffb0]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:505) ~[spigot-1.14.jar:git-Spigot-1eece4f-6ceffb0]
	at org.bukkit.craftbukkit.v1_14_R1.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:692) ~[spigot-1.14.jar:git-Spigot-1eece4f-6ceffb0]
	at net.minecraft.server.v1_14_R1.EntityLiving.d(EntityLiving.java:1359) ~[spigot-1.14.jar:git-Spigot-1eece4f-6ceffb0]
	at net.minecraft.server.v1_14_R1.EntityLiving.die(EntityLiving.java:1316) ~[spigot-1.14.jar:git-Spigot-1eece4f-6ceffb0]
	at net.minecraft.server.v1_14_R1.EntityLiving.damageEntity(EntityLiving.java:1163) ~[spigot-1.14.jar:git-Spigot-1eece4f-6ceffb0]
	at net.minecraft.server.v1_14_R1.EntityMonster.damageEntity(SourceFile:71) ~[spigot-1.14.jar:git-Spigot-1eece4f-6ceffb0]
	at net.minecraft.server.v1_14_R1.EntityZombie.damageEntity(EntityZombie.java:261) ~[spigot-1.14.jar:git-Spigot-1eece4f-6ceffb0]
	at net.minecraft.server.v1_14_R1.EntityHuman.attack(EntityHuman.java:1003) ~[spigot-1.14.jar:git-Spigot-1eece4f-6ceffb0]
	at net.minecraft.server.v1_14_R1.EntityPlayer.attack(EntityPlayer.java:1527) ~[spigot-1.14.jar:git-Spigot-1eece4f-6ceffb0]
	at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1889) ~[spigot-1.14.jar:git-Spigot-1eece4f-6ceffb0]
	at net.minecraft.server.v1_14_R1.PacketPlayInUseEntity.a(SourceFile:69) ~[spigot-1.14.jar:git-Spigot-1eece4f-6ceffb0]
	at net.minecraft.server.v1_14_R1.PacketPlayInUseEntity.a(SourceFile:13) ~[spigot-1.14.jar:git-Spigot-1eece4f-6ceffb0]
	at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:13) ~[spigot-1.14.jar:git-Spigot-1eece4f-6ceffb0]
	at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) [spigot-1.14.jar:git-Spigot-1eece4f-6ceffb0]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(SourceFile:135) [spigot-1.14.jar:git-Spigot-1eece4f-6ceffb0]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [spigot-1.14.jar:git-Spigot-1eece4f-6ceffb0]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(SourceFile:114) [spigot-1.14.jar:git-Spigot-1eece4f-6ceffb0]
	at net.minecraft.server.v1_14_R1.MinecraftServer.aW(MinecraftServer.java:895) [spigot-1.14.jar:git-Spigot-1eece4f-6ceffb0]
	at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:888) [spigot-1.14.jar:git-Spigot-1eece4f-6ceffb0]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(SourceFile:123) [spigot-1.14.jar:git-Spigot-1eece4f-6ceffb0]
	at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:872) [spigot-1.14.jar:git-Spigot-1eece4f-6ceffb0]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:805) [spigot-1.14.jar:git-Spigot-1eece4f-6ceffb0]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]
Caused by: java.lang.IllegalArgumentException: No enum constant org.bukkit.entity.Villager.Profession.HUSK
	at java.lang.Enum.valueOf(Unknown Source) ~[?:1.8.0_211]
	at org.bukkit.entity.Villager$Profession.valueOf(Villager.java:1) ~[spigot-1.14.jar:git-Spigot-1eece4f-6ceffb0]
	at one.lindegaard.MobHunting.rewards.RewardManager.getMobEnabled(RewardManager.java:2333) ~[?:?]
	at one.lindegaard.MobHunting.MobHuntingManager.onMobDeath(MobHuntingManager.java:1077) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_211]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_211]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_211]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_211]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[spigot-1.14.jar:git-Spigot-1eece4f-6ceffb0]
	... 25 more

**Comment by Rocologo** [comment] 2019-05-12 19:35
Do you know which mob was killed?

**Comment by kopper45** [comment] 2019-05-12 19:37
it was a zombie. Creepers for whatever reason seem to work now

**Comment by Rocologo** [comment] 2019-05-12 19:39
Thanks, now I can test on a Zombie to fix this bug.

**Comment by kopper45** [comment] 2019-05-12 19:44
Also seems to affect zombie pigman too.

**Comment by Rocologo** [comment] 2019-05-12 20:44
Yes, i think this is related to the zombie family. I will ser if i can fix this tomorrow

**Comment by Rocologo** [comment] 2019-05-15 20:54
Please check v6.5.7

**Comment by Rocologo** [comment] 2019-05-17 08:28
Fixed in newest version

**Closed by Rocologo** 2019-05-17 08:28 UTC
Labels: More information is needed
