### ISSUE TITLE
You can take Items out of InventoryGUI

### ISSUE THREAD

**Issue by Maxetto** [Rocologo/MobHunting#84] opened 2016-08-01 14:47 UTC
As title says, with latest dev build and Spigot 1.8.8, I can take items out of the InventoryGUI.

Plus, they aren't translated.

**Comment by Rocologo** [comment] 2016-08-01 15:28
You need to give me more details on how to reproduce the error. I cant take items out of the inventories.

**Comment by Maxetto** [comment] 2016-08-01 15:35
I have Spigot 1.8.8, MobHunting B83, "use_gui_for_bounties: true" and one Bounty set to a Player for $1000.

I can do /mh bounty and take away the head, drop it, burn it, sell it, etc.

**Comment by Maxetto** [comment] 2016-08-01 16:49
As for Achievements, without the GUI it says:
"You completed 4 out of 54 achievements:
<empty_string>
In progress: <empty>"

**Comment by Maxetto** [comment] 2016-08-01 16:52
Nevermind for the achievements. I just saw that their price went to 0 automatically for some reason.

**Comment by Rocologo** [comment] 2016-08-01 16:53
And I cant take heads out of the bounty inventory. The inventory closed immediately when I click the mouse button - I cant drag the heads or anything. If I click anywhere on the screen the gui closes. 

What are you doing differently? I cant fix a problem I cant reproduce. :-|

(And why are you now talking about achievements again????  We will never find your problem if you mix everything all the time. ) This issues is about taking items out of the inventory.

**Comment by Rocologo** [comment] 2016-08-01 16:54
The achivements price dont go down to zero automatically - I have not made such a feature.

**Comment by Maxetto** [comment] 2016-08-01 17:08
I mean, they probably went to 0 after I enclosed them in quotes :/

Anyway, it's only the Bounty GUI that has this problem.

I just do /mh bounty and I can move the inventory to my likings.

Can you try with Spigot 1.8.8 (git-Spigot-db6de12-18fbb24)?

**Comment by Rocologo** [comment] 2016-08-01 17:14
I have just tested on my 1.8.8 test server and I still cant take heads out ???

**Comment by Rocologo** [comment] 2016-08-01 17:15
This is what I seen in the server console when /mh debug is enabled.

> [19:12:53 INFO]: Rocologo issued server command: /mh bounty
> [19:12:55 INFO]: [MobHunting][Debug] BountyManager: Player clicked on inventory - closing now

**Comment by Rocologo** [comment] 2016-08-01 17:15
I will not be around the next hours.

**Comment by Maxetto** [comment] 2016-08-01 17:18
I don't get this Debug message.

You can see the bug at 01:51:55 there: https://www.twitch.tv/m4x3tto/v/81153298

Luckly for us, I was live.

**Comment by Rocologo** [comment] 2016-08-01 19:05
Yes its a perfect proof - but I believed you anyway. And its really strange. You should not be able do what you are doing. I need to find out what de difference is between your installation and mine. Maybe it is something with the translation... not that I can see why that should make a difference here.

**Comment by Rocologo** [comment] 2016-08-01 19:16
Maybe it is the server version???

This is the info from my log, how can we see which one is the newest?

> [19:09:40] [Server thread/INFO]: This server is running CraftBukkit version git-Spigot-db6de12-d3e0b6f (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

This is my server jar, try this or let me have yours.
https://dl.dropboxusercontent.com/u/36067670/Minecraft/temp/spigot-1.8.8.jar

**Comment by Rocologo** [comment] 2016-08-01 19:18
it is like your server dont catch the InventoryClickEvent that would also explain why you don't get the debug event.

**Comment by Rocologo** [comment] 2016-08-01 20:41
I googled the problem and learned that there are both a InventoryClickEvent as well as a InventoryDragEvent. MobHunting only checked the clickevent.I have tried to drag my self and I cant do it,by maybe I do it wrong??? 

I have added code for the InventoryDragEvent for both Bounties and Achievements. 

Please try build 86 and see if you still can steal heads.

**Comment by Maxetto** [comment] 2016-08-01 21:44
Nope, I'm still able to move items in my inventory.

I guess the BountyManager fails to initialize correctly, since after a restart it says there aren't any bounties, while there are 2 inside the Database.

**Comment by Maxetto** [comment] 2016-08-01 21:51
Like, this is the DB:
![db](https://cloud.githubusercontent.com/assets/1360752/17310118/b86cb746-5842-11e6-9cf3-ca70cb230421.png)

And this is what Minecraft outputs:
![mc](https://cloud.githubusercontent.com/assets/1360752/17310117/b86a66bc-5842-11e6-811f-add460506a99.png)

Note that I didn't use the GUI to get a better screen and that this $10 bounty was applied after the restart.

**Comment by Rocologo** [comment] 2016-08-02 06:12
When you type /mh reload the plugin read your config.yml and then playerSettings for all players who is online and then bounties on all player who is online. My guess is that you are player 1 so it is line 1 and 2 which should be left after a reload. 

But before solving the bounty problem i want to solve the inventory problem because this could be root cause for your problems. 

Please let me have a copy of your spigot.jar

Also i have thought about if it could be the client. Do you use a standard client or a hacked one. Optifine is not a problem.

**Comment by Rocologo** [comment] 2016-08-02 06:13
I would like to see a full log on a server restart, so i can see that everything looks fine. Use pastebin.com

**Comment by Rocologo** [comment] 2016-08-02 09:12
Also I would like you to try build 89. 

I found this note in the documentation. In build 89 I use BukkitScheduler.runTask(Plugin, Runnable)
like they say I should. (https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/inventory/InventoryClickEvent.html)

**Comment by Rocologo** [comment] 2016-08-02 10:07
you dont need to test build 87.I found a bug.

**Comment by Rocologo** [comment] 2016-08-02 11:07
you dont need to test build 87.I found a bug.  try build 88 instead.

**Comment by Maxetto** [comment] 2016-08-02 11:50
Tested build 88, the bug was not fixed. After restarting the server, only the $10 bounty was loaded into the plugin. I can still move items inside the GUI. /mh reload doesn't load the other 2 bounties.

This is my Spigot version: https://db.tt/zc6gDTcR
And, as you might have seen in the Live, I'm using Vanilla with Optifine and Shaders (integrated with Optifine)

**Comment by Rocologo** [comment] 2016-08-02 18:03
I have tried your spigot188.jar file - no luck. I could not take out heads. No matter what I tried.

I checked you log - no problems. Everything looks fine. 

I thought it could be a conflict with another plugin (especially Inventory plugins) so I installed OpenInv2.3.9 but still no success.

I'm simply out of ideas now - I dont know why you can take heads out and I cant reproduce it. 

You could test it on my PROD server mc.lindegaard.one - my guess is that you cant do it there. So we need to find the difference to solve the issue. I cant solve an issue I cant reproduce.

**Comment by Maxetto** [comment] 2016-08-02 19:19
So, Unloading after unloading, I ended up with the bug with just those 5 plugins and versions:

PlugMan 2.0.8
PermissionsEx 1.23.4
Vault 1.5.6-b49
WorldEdit 6.1.1-SNAPSHOT;3482-867e59b
MobHunting 3.3.9-SNAPSHOT

I can't try unloading more.

**Comment by Rocologo** [comment] 2016-08-02 22:02
I use the same plugins in the same versions. Its SO strange....

I will try to use your mobhunting folder tomorrow ... i have to sleep now.

**Comment by Rocologo** [comment] 2016-08-12 09:03
I was thinking that it could something that only happens when two players open the gui at the same time. This is something I have never tried - because I'm all alone on my test server (on my laptop).

hmm. 

Could you see if you can take heads out when you are all alone on the server?

**Comment by Maxetto** [comment] 2016-08-12 11:42
I always tried it alone.

**Comment by Rocologo** [comment] 2016-08-12 12:26
Hi, I cant replicate the bug, so I need your help testing the change. I hope I fixed the error too, and then it has been a very good day :-)

Please test newest build +98 on my Jenkins server
http://jenkins.lindegaard.one:8180/job/MobHunting/

Thank you

**Comment by Rocologo** [comment] 2016-08-12 12:28
I just saw your note - that you always tried it alone, this make me not so sure it is solved. I assumed this was the root cause :-( 

Anyway - please give it a try.

**Comment by Maxetto** [comment] 2016-08-12 13:01
Tried it, still no luck :/

**Comment by Rocologo** [comment] 2016-12-14 11:25
Hi Maxetto. Is this still a problem?

**Comment by Maxetto** [comment] 2016-12-14 12:59
@Rocologo I don't know, I haven't updated the plugin since.

Is the latest version still compatible with 1.8.8?

**Comment by Rocologo** [comment] 2016-12-14 15:25
Yes, I have checked that V4.2.4 starts without errors on my test server, but I havnt tested everything. I  still support mc1.7.9 R0.2 to mc 1.11, and i have no reason to believe that anything is broken. And if you find a problem i will fix it (except the inventory problem, i have idea on how to solve/reproduce the problem) there are more than 300 servers using MobHunting, but are the only one who seems to have this problem.

**Comment by Maxetto** [comment] 2016-12-14 22:57
You said that it's compatible with 1.8.8, in fact is not... partially.
I'm getting this error everytime a Mob spawns:
```
[23:54:02] [Server thread/ERROR]: Could not pass event CreatureSpawnEvent to MobHunting v4.2.5-SNAPSHOT-B215
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[Spigot188.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[Spigot188.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [Spigot188.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [Spigot188.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callCreatureSpawnEvent(CraftEventFactory.java:277) [Spigot188.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.World.addEntity(World.java:1015) [Spigot188.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.SpawnerCreature.a(SpawnerCreature.java:182) [Spigot188.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.WorldServer.doTick(WorldServer.java:227) [Spigot188.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:770) [Spigot188.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [Spigot188.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [Spigot188.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [Spigot188.jar:git-Spigot-21fe707-e1ebe52]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
Caused by: java.lang.NoClassDefFoundError: net/elseland/xikage/MythicMobs/API/Exceptions/InvalidMobTypeException
	at one.lindegaard.MobHunting.ConfigManager.getBaseKillPrize(ConfigManager.java:1608) ~[?:?]
	at one.lindegaard.MobHunting.MobHuntingManager.bonusMobSpawn(MobHuntingManager.java:1298) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor94.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_91]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_91]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[Spigot188.jar:git-Spigot-21fe707-e1ebe52]
	... 12 more
Caused by: java.lang.ClassNotFoundException: net.elseland.xikage.MythicMobs.API.Exceptions.InvalidMobTypeException
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_91]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[Spigot188.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[Spigot188.jar:git-Spigot-21fe707-e1ebe52]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_91]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_91]
	at one.lindegaard.MobHunting.ConfigManager.getBaseKillPrize(ConfigManager.java:1608) ~[?:?]
	at one.lindegaard.MobHunting.MobHuntingManager.bonusMobSpawn(MobHuntingManager.java:1298) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor94.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_91]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_91]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[Spigot188.jar:git-Spigot-21fe707-e1ebe52]
	... 12 more
```

However I have not MythicMobs, neither I had it in the past.
I think I'll fix this by manually disabling MythicMobs integration in the config, but I wanted to report this to you anyway.

Gonna try Bounty bug after config/translation update.

**Comment by Maxetto** [comment] 2016-12-15 00:03
So, I have fixed the error by downgrading to V4.2.4 (It seems you forgot an "IF" statement on loading the config, based on the latest commit).

However, I'm getting this error on start:
```
[00:53:32] [Server thread/WARN]: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Cannot add or update a child row: a foreign key constraint fails (`minecraft`.`#sql-58f_370f3aa`, CONSTRAINT `mh_Achievements_Player_Id` FOREIGN KEY (`PLAYER_ID`) REFERENCES `mh_Players` (`PLAYER_ID`) ON DELETE CASCADE)
[00:53:32] [Server thread/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[00:53:32] [Server thread/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[00:53:32] [Server thread/WARN]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[00:53:32] [Server thread/WARN]: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[00:53:32] [Server thread/WARN]: 	at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
[00:53:32] [Server thread/WARN]: 	at com.mysql.jdbc.Util.getInstance(Util.java:382)
[00:53:32] [Server thread/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1039)
[00:53:32] [Server thread/WARN]: 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3593)
[00:53:32] [Server thread/WARN]: 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3525)
[00:53:32] [Server thread/WARN]: 	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1986)
[00:53:32] [Server thread/WARN]: 	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2140)
[00:53:32] [Server thread/WARN]: 	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2620)
[00:53:32] [Server thread/WARN]: 	at com.mysql.jdbc.StatementImpl.executeUpdate(StatementImpl.java:1662)
[00:53:32] [Server thread/WARN]: 	at com.mysql.jdbc.StatementImpl.executeUpdate(StatementImpl.java:1581)
[00:53:32] [Server thread/WARN]: 	at one.lindegaard.MobHunting.storage.DatabaseDataStore.migrate_mh_PlayersFromV2ToV3(DatabaseDataStore.java:1401)
[00:53:32] [Server thread/WARN]: 	at one.lindegaard.MobHunting.storage.DatabaseDataStore.initialize(DatabaseDataStore.java:193)
[00:53:32] [Server thread/WARN]: 	at one.lindegaard.MobHunting.MobHunting.onEnable(MobHunting.java:128)
[00:53:32] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
[00:53:32] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340)
[00:53:32] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[00:53:32] [Server thread/WARN]: 	at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:285)
[00:53:32] [Server thread/WARN]: 	at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:238)
[00:53:32] [Server thread/WARN]: 	at com.rylinaux.plugman.util.PluginUtil.reload(PluginUtil.java:299)
[00:53:32] [Server thread/WARN]: 	at com.rylinaux.plugman.command.ReloadCommand.execute(ReloadCommand.java:122)
[00:53:32] [Server thread/WARN]: 	at com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:104)
[00:53:32] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[00:53:32] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[00:53:32] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641)
[00:53:32] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchServerCommand(CraftServer.java:627)
[00:53:32] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.aO(DedicatedServer.java:412)
[00:53:32] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:375)
[00:53:32] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
[00:53:32] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[00:53:32] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)
```
and the integration with Citizens is not working with Citizens v2.0.16 (build 1308)
`[MobHunting][ERROR] MobHunting could not register with [Citizens] please check if [Citizens] is compatible with the server [1.8.8-R0.1-SNAPSHOT]`

and this bug is still not fixed :/
I'm running latest Spigot build for 1.8.8 (The one that has Timings fixed): git-Spigot-21fe707-e1ebe52 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)


I truly don't get why it doesn't work well for me. It's like the event is not even registered.

I might do some internal debugging if you can tell me the events you listen for in order to cancel the GUI movements.

**Comment by Rocologo** [comment] 2016-12-15 10:43
I still have my "Spigot 1.8.8 Maxetto" Test server with a copy of your plugins including Citizens and without MythicMobs. I will test v4.2.5 on this one and make a new release for you.

**Comment by Rocologo** [comment] 2016-12-15 10:55
If you upgrade MythicMobs to V2.5.1 including MythicLib-0.0.1-SNAPSHOT Then MobHunting works.

**Comment by Maxetto** [comment] 2016-12-15 11:33
@Rocologo The point is that I don't have MythicMobs, neither I want to install it in order to get 4.2.5 version working.

Something is not working in your MythicMobs detection, I guess the problem is in this line:
https://github.com/Rocologo/MobHunting/blob/master/src/one/lindegaard/MobHunting/compatibility/MythicMobsCompat.java#L49

As I can see, no other Compat is calling the API upon class initialization, they just try to get the Plugin.

**Comment by Rocologo** [comment] 2016-12-15 12:12
I understood that and I will make a new build in less than 30 min where you **dont** need MythicMobs. I need to make some more tests and then I will make a new SNAPSHOT for you.

**Comment by Rocologo** [comment] 2016-12-15 12:23
Build 217 or newer should without MythicMobs, and with if MythicMobs is 2.5.1 or newer. The missiing text in /mh help is added too.
http://jenkins.lindegaard.one:8180/job/MobHunting/217/

**Comment by Maxetto** [comment] 2017-01-08 03:26
I was thinking... Have you already tried with a different language?
Might be some kind of NBT/.equals() Bug due to different languages than expected.

You should already have my folder with my translation. In case you don't, you can find it in one of my replies on this ticket.

**Comment by Rocologo** [comment] 2017-01-08 07:31
Yes, I have still the copy of your. But the problem was that when I ran the server on my laptop I was NOT  able to take out heads. Which is really strange....

**Comment by Maxetto** [comment] 2017-06-09 14:04
Regarding this, it's still a problem even with PaperSpigot 1.8.8 and MobHunting v4.9.2.

Actually I think this is not a fault of the BountyGUI, but the entire Bounty system.
I still have database entries of the test bounties I created with this ticket, but yet they should be removed because of expiration.

Maybe it's SQL related (collations?)

**Comment by Rocologo** [comment] 2017-06-10 11:32
Unfortunately I cant replicate this error :-( so I need your help to see if changes works. 

Please test build 398
https://fractal.lindegaard.one:8181/job/MobHunting/

**Comment by Maxetto** [comment] 2017-06-10 12:09
Not yet fixed... and also, there's an error but it may have been related to PlugMan's reload.

```
10.06 14:07:49 [Server] WARN Task #415668 for MobHunting v4.9.5-SNAPSHOT-B398 generated an exception
10.06 14:07:49 [Server] INFO java.lang.NullPointerException
10.06 14:07:49 [Server] INFO at one.lindegaard.MobHunting.bounty.BountyManager.delete(BountyManager.java:345) ~[?:?]
10.06 14:07:49 [Server] INFO at one.lindegaard.MobHunting.bounty.BountyManager$5.onCompleted(BountyManager.java:275) ~[?:?]
10.06 14:07:49 [Server] INFO at one.lindegaard.MobHunting.bounty.BountyManager$5.onCompleted(BountyManager.java:257) ~[?:?]
10.06 14:07:49 [Server] INFO at one.lindegaard.MobHunting.storage.DataStoreManager$CallbackCaller.run(DataStoreManager.java:324) ~[?:?]
10.06 14:07:49 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59) ~[patched.jar:git-PaperSpigot-"4c7641d"]
10.06 14:07:49 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:352) [patched.jar:git-PaperSpigot-"4c7641d"]
10.06 14:07:49 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:783) [patched.jar:git-PaperSpigot-"4c7641d"]
10.06 14:07:49 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [patched.jar:git-PaperSpigot-"4c7641d"]
10.06 14:07:49 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [patched.jar:git-PaperSpigot-"4c7641d"]
10.06 14:07:49 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [patched.jar:git-PaperSpigot-"4c7641d"]
10.06 14:07:49 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
```

**Comment by Rocologo** [comment] 2017-06-10 15:22
Dont mix the bugs, please...

**Comment by Rocologo** [comment] 2017-06-10 15:39
1) first run /mobhunt database convert-to-utf8
2) The install Builds 401 to see if this fixes the Bounty error

I still dont know how to solve the Inventory error, because I cant replicate this :-(

**Comment by Rocologo** [comment] 2017-06-14 16:24
I once again tried to fix the problem with the inventory..... its so annoying that I cant replicate the bug. If this was possible I could fix the problem... Please test V4.9.5

**Comment by Rocologo** [comment] 2017-07-11 17:55
@Maxetto : Have you upgraded to Minecraft 1.12 ? Are you still able to take items out if the inventory?

**Comment by Maxetto** [comment] 2017-07-11 20:04
No, I didn't upgrade yet.

**Comment by Rocologo** [comment] 2019-07-06 18:32
still on 1.8.8 ? :-)

**Comment by Maxetto** [comment] 2019-07-06 21:13
Nope, i closed the server. :P

**Comment by Rocologo** [comment] 2019-07-07 11:33
Okay. Tha

**Comment by Rocologo** [comment] 2019-07-07 11:34
Okay thanks. Then I will close this ticket.

**Closed by Rocologo** 2019-07-07 11:34 UTC
Labels: bug
