### ISSUE TITLE
Fishing error

### ISSUE THREAD

**Issue by Sikatsu** [Rocologo/MobHunting#125] opened 2017-02-04 18:16 UTC
Hey,

Just saw that I have 2 fishing errors in my console. http://pastebin.com/yYNVGZHF

**Comment by Rocologo** [comment] 2017-02-04 19:40
Please use newest build
http://jenkins.lindegaard.one:8180/job/MobHunting/

**Comment by Sikatsu** [comment] 2017-02-04 19:43
Thanks for fixing. I test the versions on my test server until fishing is stable, however I do not know how to reproduce this error. Let me know once you need me to test something about the other errors on here.

**Comment by Rocologo** [comment] 2017-02-04 22:30
You cant reproduce it. The bug is fixed. 

I was not aware the you could catch a Zombie or a player with a fishing rod. Which would cause this error. I now test if it is an Item. :-) 

I close this ticket.

**Closed by Rocologo** 2017-02-04 22:30 UTC
