### ISSUE TITLE
All Mobhunting heads break off of walls when you break 1 head

### ISSUE THREAD

**Issue by Zoneman1972** [Rocologo/MobHunting#565] opened 2019-09-07 03:55 UTC
If you have a wall of MobHunting heads and you either place a torch near them or you break 1 of them, the whole lot will drop off of the wall.
Minecraft Version 1.14.4
MobHunting Version 6.8.5
Paper version 183

**Comment by Rocologo** [comment] 2019-09-07 08:23
I cant reproduce the problem. Maybe I have already fixed this issue (its something I have been working on).

Please update to newest release.

**Comment by Sikatsu** [comment] 2019-09-07 14:09
@Rocologo Actually, this was suppose to be fixed but it's still happening for me aswell.

**Comment by Rocologo** [comment] 2019-09-07 14:49
Then you have to explain your setup. Because I have testet hvis.

**Comment by Rocologo** [comment] 2019-09-07 14:50
Paste a Sceenshot Before you break one head

**Comment by Rocologo** [comment] 2019-09-11 17:57
I tested this again, and Im not able reproduce the problem.

I found another bug, which could make the heads loose its value when they are placed as a block. This is fixed in MobHunting v6.8.9 / BagOfGold v2.8.9

**Comment by Rocologo** [comment] 2019-10-07 17:33
I think I have found the bug now, please help me with the testing. 

The issue appeared when you only use MobHunting (but still has a BagOfGold folder) in this case the rewards was deleted because they was not in BagOfGold/rewards.yml

**Comment by Rocologo** [comment] 2019-10-07 17:41
I will make two new releases now

**Comment by Rocologo** [comment] 2019-10-09 17:52
Please test v6.9.5. Broken heads should be fixed now. Please try some new heads as old heads might already be broken now and I cant fix them if they is already broken.

**Closed** 2020-06-30 18:56 UTC
Labels: Fixed - To be tested
